//! What the script scan admits (REG-032): the standard browser globals a
//! component script may name, the method names it may call, and the rules
//! that apply to the arguments of the ones that load, parse or run
//! something. Everything not listed is refused.

/// Global identifiers a script may read. Each is a standard browser or
/// language API; the ones that load or run something (`fetch`, `location`,
/// the timers, `XMLHttpRequest`, `WebSocket`, `EventSource`, `Image`,
/// `Audio`, `Request`) have their arguments checked where they are used.
pub const ADMITTED_GLOBALS: &[&str] = &[
    "AbortController",
    "AbortSignal",
    "Array",
    "Audio",
    "Boolean",
    "CSS",
    "CustomEvent",
    "DOMException",
    "Date",
    "DocumentFragment",
    "Element",
    "Error",
    "Event",
    "EventSource",
    "EventTarget",
    "FocusEvent",
    "FormData",
    "HTMLAnchorElement",
    "HTMLButtonElement",
    "HTMLDetailsElement",
    "HTMLDialogElement",
    "HTMLElement",
    "HTMLFormElement",
    "HTMLImageElement",
    "HTMLInputElement",
    "HTMLLabelElement",
    "HTMLOptionElement",
    "HTMLSelectElement",
    "HTMLTemplateElement",
    "HTMLTextAreaElement",
    "Headers",
    "Image",
    "Infinity",
    "InputEvent",
    "IntersectionObserver",
    "Intl",
    "JSON",
    "KeyboardEvent",
    "Map",
    "Math",
    "MouseEvent",
    "MutationObserver",
    "NaN",
    "Node",
    "NodeFilter",
    "Number",
    "Object",
    "PointerEvent",
    "Promise",
    "RangeError",
    "Request",
    "ResizeObserver",
    "Set",
    "String",
    "SubmitEvent",
    "Symbol",
    "Text",
    "TextDecoder",
    "TextEncoder",
    "TypeError",
    "URL",
    "URLSearchParams",
    "WeakMap",
    "WeakSet",
    "WebSocket",
    "XMLHttpRequest",
    "cancelAnimationFrame",
    "clearInterval",
    "clearTimeout",
    "console",
    "crypto",
    "customElements",
    "decodeURIComponent",
    "document",
    "encodeURIComponent",
    "fetch",
    "getComputedStyle",
    "globalThis",
    "history",
    "isFinite",
    "isNaN",
    "location",
    "matchMedia",
    "open",
    "parseFloat",
    "parseInt",
    "performance",
    "queueMicrotask",
    "requestAnimationFrame",
    "self",
    "setInterval",
    "setTimeout",
    "structuredClone",
    "undefined",
    "window",
];

/// The global object under its names. A script may use one only to read
/// an admitted global from it, to write a global of its own, or in a
/// `typeof` or comparison, so the global object never reaches a variable
/// through which an unlisted global could be read.
pub const GLOBAL_OBJECTS: &[&str] = &["window", "self", "globalThis"];

/// Method names a script may call on any receiver: standard DOM, events,
/// collections, strings, numbers, promises and the like. The ones in
/// [`ARGUMENT_RULES`] have their arguments checked.
pub const ADMITTED_METHODS: &[&str] = &[
    "abort",
    "abs",
    "add",
    "addEventListener",
    "addListener",
    "after",
    "animate",
    "append",
    "appendChild",
    "apply",
    "assign",
    "at",
    "before",
    "bind",
    "blur",
    "call",
    "cancel",
    "catch",
    "ceil",
    "charAt",
    "charCodeAt",
    "checkValidity",
    "clear",
    "clearInterval",
    "clearTimeout",
    "click",
    "cloneNode",
    "close",
    "closest",
    "codePointAt",
    "concat",
    "contains",
    "createDocumentFragment",
    "createElement",
    "createElementNS",
    "createTextNode",
    "define",
    "delete",
    "disconnect",
    "dispatchEvent",
    "encodeURIComponent",
    "endsWith",
    "entries",
    "error",
    "escape",
    "every",
    "exec",
    "fetch",
    "fill",
    "filter",
    "finally",
    "find",
    "findIndex",
    "findLast",
    "findLastIndex",
    "flat",
    "flatMap",
    "floor",
    "focus",
    "forEach",
    "format",
    "freeze",
    "from",
    "fromEntries",
    "get",
    "getAttribute",
    "getBoundingClientRect",
    "getClientRects",
    "getComputedStyle",
    "getElementById",
    "getElementsByClassName",
    "getElementsByTagName",
    "getFullYear",
    "getMonth",
    "getDate",
    "getDay",
    "getHours",
    "getMinutes",
    "getSeconds",
    "getRandomValues",
    "getRootNode",
    "getTime",
    "has",
    "hasAttribute",
    "hasChildNodes",
    "hasOwn",
    "hasPointerCapture",
    "includes",
    "indexOf",
    "info",
    "insertAdjacentElement",
    "insertAdjacentText",
    "insertBefore",
    "is",
    "isArray",
    "isFinite",
    "isInteger",
    "isNaN",
    "item",
    "join",
    "keys",
    "lastIndexOf",
    "localeCompare",
    "log",
    "map",
    "match",
    "matchAll",
    "matchMedia",
    "matches",
    "max",
    "min",
    "next",
    "normalize",
    "now",
    "observe",
    "open",
    "padEnd",
    "padStart",
    "parse",
    "parseFloat",
    "parseInt",
    "pop",
    "pow",
    "prepend",
    "preventDefault",
    "push",
    "pushState",
    "querySelector",
    "querySelectorAll",
    "queueMicrotask",
    "random",
    "randomUUID",
    "reduce",
    "reduceRight",
    "releasePointerCapture",
    "reload",
    "remove",
    "removeAttribute",
    "removeChild",
    "removeEventListener",
    "removeListener",
    "repeat",
    "replace",
    "replaceAll",
    "replaceChild",
    "replaceChildren",
    "replaceState",
    "replaceWith",
    "reportValidity",
    "requestAnimationFrame",
    "requestSubmit",
    "reset",
    "resolve",
    "reverse",
    "round",
    "scroll",
    "scrollBy",
    "scrollIntoView",
    "scrollTo",
    "search",
    "select",
    "sendBeacon",
    "set",
    "setAttribute",
    "setAttributeNS",
    "setCustomValidity",
    "setInterval",
    "setPointerCapture",
    "setProperty",
    "setRangeText",
    "setSelectionRange",
    "setTimeout",
    "shift",
    "show",
    "showModal",
    "sign",
    "slice",
    "some",
    "sort",
    "splice",
    "split",
    "sqrt",
    "startsWith",
    "stopImmediatePropagation",
    "stopPropagation",
    "stringify",
    "structuredClone",
    "submit",
    "substring",
    "supports",
    "test",
    "then",
    "toFixed",
    "toISOString",
    "toLocaleString",
    "toLowerCase",
    "toSorted",
    "toString",
    "toUpperCase",
    "toggle",
    "toggleAttribute",
    "trim",
    "trimEnd",
    "trimStart",
    "trunc",
    "unobserve",
    "unshift",
    "upgrade",
    "values",
    "warn",
    "whenDefined",
    "all",
    "allSettled",
    "any",
    "race",
    "reject",
];

/// Constructors a script may call with `new`. The ones that fetch take a
/// URL that must stay on the application's origin, and the observers and
/// `Promise` take a callback that must resolve.
pub const ADMITTED_CONSTRUCTORS: &[&str] = &[
    "AbortController",
    "Array",
    "Audio",
    "CustomEvent",
    "DOMException",
    "Date",
    "Error",
    "Event",
    "EventSource",
    "FocusEvent",
    "FormData",
    "Headers",
    "Image",
    "InputEvent",
    "IntersectionObserver",
    "KeyboardEvent",
    "Map",
    "MouseEvent",
    "MutationObserver",
    "PointerEvent",
    "Promise",
    "RangeError",
    "Request",
    "ResizeObserver",
    "Set",
    "SubmitEvent",
    "TextDecoder",
    "TextEncoder",
    "TypeError",
    "URL",
    "URLSearchParams",
    "WeakMap",
    "WeakSet",
    "WebSocket",
    "XMLHttpRequest",
];

/// Property names a script may not touch at all: each reaches code
/// execution, HTML parsing, the global object or a way around the other
/// rules (REG-032).
pub const REFUSED_PROPERTIES: &[&str] = &[
    "eval",
    "Function",
    "constructor",
    "__proto__",
    "__defineGetter__",
    "__defineSetter__",
    "__lookupGetter__",
    "__lookupSetter__",
    "caller",
    "callee",
    "attributes",
    "write",
    "writeln",
    "insertAdjacentHTML",
    "setHTMLUnsafe",
    "setHTML",
    "createContextualFragment",
    "parseFromString",
    "parseHTMLUnsafe",
    "attachShadow",
    "execCommand",
    "importScripts",
    "insertRule",
    "replaceSync",
    "setNamedItem",
    "setNamedItemNS",
    "getNamedItem",
    "getNamedItemNS",
    "getAttributeNode",
    "getAttributeNodeNS",
    "setAttributeNode",
    "setAttributeNodeNS",
    "createAttribute",
    "createAttributeNS",
    "srcdoc",
    "defaultView",
    "view",
    "contentWindow",
    "contentDocument",
    "opener",
    "parent",
    "top",
    "frames",
    "window",
    "self",
    "globalThis",
    "Reflect",
    "Proxy",
    "WebAssembly",
    "Worker",
    "SharedWorker",
    "serviceWorker",
    "trustedTypes",
    "postMessage",
];

/// Property names a script may read but not write.
pub const READ_ONLY_PROPERTIES: &[&str] = &[
    "innerHTML",
    "outerHTML",
    "prototype",
    "protocol",
    "host",
    "hostname",
    "port",
    "username",
    "password",
    "origin",
    "domain",
    "cookie",
    "baseVal",
    "animVal",
    "content",
    "httpEquiv",
    "text",
];

/// Properties whose value is a URL the browser loads or navigates to; a
/// value written to one must be a constant on the application's origin.
pub const URL_PROPERTIES: &[&str] = &[
    "href",
    "src",
    "srcset",
    "action",
    "formAction",
    "poster",
    "data",
    "ping",
    "codeBase",
    "cite",
    "longDesc",
    "lowsrc",
    "background",
    "location",
    "imageSrcset",
];

/// Attribute names that carry a URL, in their lowercase form.
pub const URL_ATTRIBUTES: &[&str] = &[
    "href",
    "src",
    "srcset",
    "action",
    "formaction",
    "poster",
    "data",
    "xlink:href",
    "ping",
    "background",
    "cite",
    "longdesc",
    "lowsrc",
    "dynsrc",
    "codebase",
    "manifest",
    "icon",
    "imagesrcset",
    "usemap",
    "archive",
    "classid",
];

/// Elements a script may not create: each runs or loads what the scan
/// cannot read, or changes how the page resolves URLs.
pub const REFUSED_ELEMENTS: &[&str] = &[
    "script",
    "iframe",
    "frame",
    "frameset",
    "object",
    "embed",
    "applet",
    "portal",
    "base",
    "link",
    "meta",
    "style",
    "animate",
    "animatemotion",
    "animatetransform",
    "set",
    "foreignobject",
    "handler",
    "listener",
];

/// CSS properties whose value may name a resource; a script that writes
/// one must write a constant the CSS scan admits.
pub const URL_CSS_PROPERTIES: &[&str] = &[
    "background",
    "background-image",
    "border-image",
    "border-image-source",
    "list-style",
    "list-style-image",
    "mask",
    "mask-image",
    "-webkit-mask",
    "-webkit-mask-image",
    "webkit-mask",
    "webkit-mask-image",
    "content",
    "cursor",
    "filter",
    "clip-path",
    "shape-outside",
    "offset-path",
    "marker",
    "marker-start",
    "marker-mid",
    "marker-end",
    "src",
];

/// Names a property or method may have that the browser calls on its own
/// (`toString` when coercing, `then` when awaiting, `handleEvent` for a
/// listener object); a value under one of them must be a function the
/// script defines.
pub const IMPLICITLY_CALLED: &[&str] = &[
    "toString",
    "valueOf",
    "then",
    "handleEvent",
    "toJSON",
    "next",
];

/// How a call's arguments are checked, by method or function name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Rule {
    /// The arguments at these positions are called back.
    Callbacks(&'static [usize]),
    /// A timer: the first argument must be a function.
    Timer,
    /// `setAttribute(name, value)` and friends: the name argument's index
    /// and the value argument's index.
    Attribute(usize, Option<usize>),
    /// `createElement(name)`: the name argument's index.
    Element(usize),
    /// A URL at this index must stay on the application's origin.
    Url(usize),
    /// `open`: a window URL or an `XMLHttpRequest` URL.
    Open,
    /// `location.assign` and `location.replace`, which share their names
    /// with string and object methods.
    Navigate,
    /// `customElements.define(name, class)`.
    Define,
    /// `style.setProperty(name, value)`.
    StyleProperty,
    /// `element.animate(keyframes)`: a keyframe may set a CSS property that
    /// names a resource.
    Keyframes,
}

/// The argument rules, by method or global function name.
pub const ARGUMENT_RULES: &[(&str, Rule)] = &[
    ("setTimeout", Rule::Timer),
    ("setInterval", Rule::Timer),
    ("requestAnimationFrame", Rule::Callbacks(&[0])),
    ("queueMicrotask", Rule::Callbacks(&[0])),
    ("addEventListener", Rule::Callbacks(&[1])),
    ("addListener", Rule::Callbacks(&[0])),
    ("forEach", Rule::Callbacks(&[0])),
    ("map", Rule::Callbacks(&[0])),
    ("filter", Rule::Callbacks(&[0])),
    ("find", Rule::Callbacks(&[0])),
    ("findIndex", Rule::Callbacks(&[0])),
    ("findLast", Rule::Callbacks(&[0])),
    ("findLastIndex", Rule::Callbacks(&[0])),
    ("some", Rule::Callbacks(&[0])),
    ("every", Rule::Callbacks(&[0])),
    ("flatMap", Rule::Callbacks(&[0])),
    ("reduce", Rule::Callbacks(&[0])),
    ("reduceRight", Rule::Callbacks(&[0])),
    ("sort", Rule::Callbacks(&[0])),
    ("toSorted", Rule::Callbacks(&[0])),
    ("from", Rule::Callbacks(&[1])),
    ("then", Rule::Callbacks(&[0, 1])),
    ("catch", Rule::Callbacks(&[0])),
    ("finally", Rule::Callbacks(&[0])),
    ("parse", Rule::Callbacks(&[1])),
    ("stringify", Rule::Callbacks(&[1])),
    ("replaceAll", Rule::Callbacks(&[1])),
    ("setAttribute", Rule::Attribute(0, Some(1))),
    ("setAttributeNS", Rule::Attribute(1, Some(2))),
    ("toggleAttribute", Rule::Attribute(0, None)),
    ("createElement", Rule::Element(0)),
    ("createElementNS", Rule::Element(1)),
    ("fetch", Rule::Url(0)),
    ("sendBeacon", Rule::Url(0)),
    ("open", Rule::Open),
    ("assign", Rule::Navigate),
    ("replace", Rule::Navigate),
    ("define", Rule::Define),
    ("setProperty", Rule::StyleProperty),
    ("animate", Rule::Keyframes),
];

/// The argument rules of constructors, by name.
pub const CONSTRUCTOR_RULES: &[(&str, Rule)] = &[
    ("Audio", Rule::Url(0)),
    ("Request", Rule::Url(0)),
    ("WebSocket", Rule::Url(0)),
    ("EventSource", Rule::Url(0)),
    ("MutationObserver", Rule::Callbacks(&[0])),
    ("ResizeObserver", Rule::Callbacks(&[0])),
    ("IntersectionObserver", Rule::Callbacks(&[0])),
    ("Promise", Rule::Callbacks(&[0])),
];

/// The rule for a method or global function name, when it has one.
pub fn rule_for(name: &str) -> Option<Rule> {
    ARGUMENT_RULES
        .iter()
        .find(|(rule_name, _)| *rule_name == name)
        .map(|(_, rule)| *rule)
}

/// The rule for a constructor name, when it has one.
pub fn constructor_rule_for(name: &str) -> Option<Rule> {
    CONSTRUCTOR_RULES
        .iter()
        .find(|(rule_name, _)| *rule_name == name)
        .map(|(_, rule)| *rule)
}
