// voku/portable-ascii 2.1.1, whose replacement map this file transcribes,
// is distributed under this license:
//
// Copyright (C) 2019 Lars Moelleken
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

//! Language overrides from voku/portable-ascii 2.1.1.
//! Only replacements that differ from the shared ASCII map are listed.
//! Source: https://github.com/voku/portable-ascii/tree/2.1.1/src/voku/helper/data

/// A language map, sorted by language and then by replacement key.
pub(super) const MAPS: &[(&str, &[(&str, &str)])] = &[
    (
        "bg",
        &[
            ("\u{416}", "Zh"),
            ("\u{419}", "Y"),
            ("\u{425}", "H"),
            ("\u{427}", "Ch"),
            ("\u{428}", "Sh"),
            ("\u{429}", "Sht"),
            ("\u{42a}", "A"),
            ("\u{42e}", "Yu"),
            ("\u{42f}", "Ya"),
            ("\u{436}", "zh"),
            ("\u{439}", "y"),
            ("\u{445}", "h"),
            ("\u{447}", "ch"),
            ("\u{448}", "sh"),
            ("\u{449}", "sht"),
            ("\u{44a}", "a"),
            ("\u{44e}", "yu"),
            ("\u{44f}", "ya"),
        ],
    ),
    (
        "da",
        &[
            ("\u{c5}", "Aa"),
            ("\u{c6}", "Ae"),
            ("\u{d8}", "Oe"),
            ("\u{e5}", "aa"),
            ("\u{f8}", "oe"),
        ],
    ),
    (
        "de",
        &[
            ("\u{c4}", "Ae"),
            ("\u{d6}", "Oe"),
            ("\u{dc}", "Ue"),
            ("\u{e4}", "ae"),
            ("\u{f6}", "oe"),
            ("\u{fc}", "ue"),
        ],
    ),
    (
        "de_at",
        &[
            ("\u{c4}", "Ae"),
            ("\u{d6}", "Oe"),
            ("\u{dc}", "Ue"),
            ("\u{df}", "sz"),
            ("\u{e4}", "ae"),
            ("\u{f6}", "oe"),
            ("\u{fc}", "ue"),
            ("\u{1e9e}", "SZ"),
        ],
    ),
    (
        "de_ch",
        &[
            ("\u{c4}", "Ae"),
            ("\u{d6}", "Oe"),
            ("\u{dc}", "Ue"),
            ("\u{e4}", "ae"),
            ("\u{f6}", "oe"),
            ("\u{fc}", "ue"),
        ],
    ),
    (
        "el",
        &[
            ("\u{395}\u{3b9}", "I"),
            ("\u{39f}\u{3b9}", "I"),
            ("\u{39f}\u{3c5}", "u"),
            ("\u{3a5}\u{3b9}", "I"),
            ("\u{3b5}\u{3b9}", "i"),
            ("\u{3bf}\u{3b9}", "i"),
            ("\u{3bf}\u{3c5}", "u"),
            ("\u{3c5}\u{3b9}", "i"),
        ],
    ),
    (
        "el__greeklish",
        &[
            ("\u{389}", "H"),
            ("\u{38e}\u{399}", "YI"),
            ("\u{38e}\u{3b9}", "Yi"),
            ("\u{395}\u{38a}", "EI"),
            ("\u{395}\u{399}", "EI"),
            ("\u{395}\u{3a5}", "EU"),
            ("\u{395}\u{3af}", "Ei"),
            ("\u{395}\u{3b9}", "EI"),
            ("\u{395}\u{3c5}", "Eu"),
            ("\u{39f}\u{38a}", "OI"),
            ("\u{39f}\u{399}", "OI"),
            ("\u{39f}\u{3a5}", "OU"),
            ("\u{39f}\u{3af}", "Oi"),
            ("\u{39f}\u{3c5}", "Ou"),
            ("\u{3a0}", "N"),
            ("\u{3a5}\u{38a}", "Yi"),
            ("\u{3a5}\u{399}", "YI"),
            ("\u{3a5}\u{3af}", "Yi"),
            ("\u{3a9}", "W"),
            ("\u{3ae}", "h"),
            ("\u{3b2}", "b"),
            ("\u{3b3}", "g"),
            ("\u{3b5}\u{3af}", "ei"),
            ("\u{3b5}\u{3c5}", "eu"),
            ("\u{3b7}", "h"),
            ("\u{3bf}\u{3af}", "oi"),
            ("\u{3bf}\u{3c5}", "ou"),
            ("\u{3c5}", "y"),
            ("\u{3c5}\u{3af}", "yi"),
            ("\u{3c7}", "x"),
            ("\u{3c9}", "w"),
            ("\u{3cd}\u{3b9}", "yi"),
        ],
    ),
    (
        "eo",
        &[
            ("\u{108}", "CX"),
            ("\u{109}", "cx"),
            ("\u{11c}", "GX"),
            ("\u{11d}", "gx"),
            ("\u{124}", "HX"),
            ("\u{125}", "hx"),
            ("\u{134}", "JX"),
            ("\u{135}", "jx"),
            ("\u{15c}", "SX"),
            ("\u{15d}", "sx"),
            ("\u{16c}", "UX"),
            ("\u{16d}", "ux"),
        ],
    ),
    (
        "fa",
        &[
            ("\u{62b}", "s"),
            ("\u{62c}", "j"),
            ("\u{630}", "z"),
            ("\u{636}", "z"),
            ("\u{638}", "z"),
            ("\u{639}", "a"),
            ("\u{642}", "gh"),
        ],
    ),
    ("fr_at", &[("\u{df}", "sz"), ("\u{1e9e}", "SZ")]),
    ("hr", &[("\u{110}", "Dj"), ("\u{111}", "dj")]),
    ("lv", &[("\u{12a}", "i"), ("\u{16a}", "u")]),
    (
        "mk",
        &[
            ("\u{408}", "J"),
            ("\u{40f}", "Dj"),
            ("\u{416}", "Zh"),
            ("\u{425}", "H"),
            ("\u{427}", "Ch"),
            ("\u{428}", "Sh"),
            ("\u{436}", "zh"),
            ("\u{445}", "h"),
            ("\u{447}", "ch"),
            ("\u{448}", "sh"),
            ("\u{45f}", "dj"),
        ],
    ),
    (
        "no",
        &[
            ("\u{c5}", "AA"),
            ("\u{d8}", "OE"),
            ("\u{e5}", "aa"),
            ("\u{f8}", "oe"),
        ],
    ),
    (
        "pt",
        &[
            ("\u{c5}", "AA"),
            ("\u{d0}", "Dj"),
            ("\u{d8}", "OE"),
            ("\u{e5}", "aa"),
            ("\u{f0}", "dj"),
            ("\u{f8}", "oe"),
        ],
    ),
    (
        "ru",
        &[
            ("\u{401}", "Yo"),
            ("\u{416}", "Zh"),
            ("\u{419}", "Y"),
            ("\u{425}", "H"),
            ("\u{426}", "Ts"),
            ("\u{427}", "Ch"),
            ("\u{428}", "Sh"),
            ("\u{429}", "Sch"),
            ("\u{42a}", ""),
            ("\u{42e}", "Yu"),
            ("\u{42f}", "Ya"),
            ("\u{436}", "zh"),
            ("\u{439}", "y"),
            ("\u{445}", "h"),
            ("\u{446}", "ts"),
            ("\u{447}", "ch"),
            ("\u{448}", "sh"),
            ("\u{449}", "sch"),
            ("\u{44a}", ""),
            ("\u{44e}", "yu"),
            ("\u{44f}", "ya"),
            ("\u{451}", "yo"),
        ],
    ),
    (
        "ru__gost_2000_b",
        &[
            ("\u{401}", "Yo"),
            ("\u{404}", ""),
            ("\u{405}", "Js"),
            ("\u{416}", "Zh"),
            ("\u{418}", "i"),
            ("\u{426}", "Cz"),
            ("\u{427}", "Ch"),
            ("\u{428}", "Sh"),
            ("\u{42a}", ""),
            ("\u{42b}", "Y'"),
            ("\u{42d}", "E'"),
            ("\u{42e}", "Yu"),
            ("\u{42f}", "Ya"),
            ("\u{436}", "zh"),
            ("\u{446}", "cz"),
            ("\u{447}", "ch"),
            ("\u{448}", "sh"),
            ("\u{44a}", ""),
            ("\u{44b}", "y'"),
            ("\u{44d}", "e'"),
            ("\u{44e}", "yu"),
            ("\u{44f}", "ya"),
            ("\u{451}", "yo"),
            ("\u{454}", ""),
            ("\u{455}", "js"),
            ("\u{460}", ""),
            ("\u{461}", ""),
            ("\u{462}", "Ye"),
            ("\u{463}", "ye"),
            ("\u{464}", ""),
            ("\u{465}", ""),
            ("\u{466}", ""),
            ("\u{467}", ""),
            ("\u{468}", ""),
            ("\u{469}", ""),
            ("\u{46a}", ""),
            ("\u{46b}", ""),
            ("\u{46c}", ""),
            ("\u{46d}", ""),
            ("\u{46e}", ""),
            ("\u{46f}", ""),
            ("\u{470}", ""),
            ("\u{471}", ""),
            ("\u{472}", "Fh"),
            ("\u{473}", "fh"),
            ("\u{474}", "Yh"),
            ("\u{475}", "yh"),
            ("\u{47e}", ""),
            ("\u{47f}", ""),
            ("\u{a64a}", ""),
            ("\u{a64b}", ""),
        ],
    ),
    (
        "ru__passport_2013",
        &[
            ("\u{404}", ""),
            ("\u{405}", ""),
            ("\u{406}", ""),
            ("\u{416}", "Zh"),
            ("\u{418}", "i"),
            ("\u{425}", "Kh"),
            ("\u{426}", "Ts"),
            ("\u{427}", "Ch"),
            ("\u{428}", "Sh"),
            ("\u{429}", "Shch"),
            ("\u{436}", "zh"),
            ("\u{445}", "kh"),
            ("\u{446}", "ts"),
            ("\u{447}", "ch"),
            ("\u{448}", "sh"),
            ("\u{449}", "shch"),
            ("\u{454}", ""),
            ("\u{455}", ""),
            ("\u{456}", ""),
            ("\u{460}", ""),
            ("\u{461}", ""),
            ("\u{462}", ""),
            ("\u{463}", ""),
            ("\u{464}", ""),
            ("\u{465}", ""),
            ("\u{466}", ""),
            ("\u{467}", ""),
            ("\u{468}", ""),
            ("\u{469}", ""),
            ("\u{46a}", ""),
            ("\u{46b}", ""),
            ("\u{46c}", ""),
            ("\u{46d}", ""),
            ("\u{46e}", ""),
            ("\u{46f}", ""),
            ("\u{470}", ""),
            ("\u{471}", ""),
            ("\u{472}", ""),
            ("\u{473}", ""),
            ("\u{474}", ""),
            ("\u{475}", ""),
            ("\u{47e}", ""),
            ("\u{47f}", ""),
            ("\u{a64a}", ""),
            ("\u{a64b}", ""),
        ],
    ),
    (
        "sr",
        &[
            ("\u{110}", "Dj"),
            ("\u{111}", "dj"),
            ("\u{425}", "H"),
            ("\u{445}", "h"),
        ],
    ),
    ("sr__cyr", &[("\u{425}", "H"), ("\u{445}", "h")]),
    ("sr__lat", &[("\u{110}", "Dj"), ("\u{111}", "dj")]),
    (
        "uk",
        &[
            ("\u{404}", "Ye"),
            ("\u{413}", "H"),
            ("\u{418}", "Y"),
            ("\u{419}", "Y"),
            ("\u{425}", "Kh"),
            ("\u{426}", "Ts"),
            ("\u{427}", "Ch"),
            ("\u{428}", "Sh"),
            ("\u{429}", "Shch"),
            ("\u{433}", "h"),
            ("\u{438}", "y"),
            ("\u{439}", "y"),
            ("\u{445}", "kh"),
            ("\u{446}", "ts"),
            ("\u{447}", "ch"),
            ("\u{448}", "sh"),
            ("\u{449}", "shch"),
            ("\u{454}", "ye"),
        ],
    ),
];
