// doctrine/inflector 2.1.0, whose rule data this file transcribes, is
// distributed under this license:
//
// Copyright (c) 2006-2015 Doctrine Project
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is furnished to do
// so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

//! Additional complete doctrine/inflector 2.1.0 rule sets.
//! Source: https://github.com/doctrine/inflector/tree/2.1.0/src/Rules

use super::inflector::{LanguageRules, RuleList};

/// Esperanto.
pub(super) const ESPERANTO: LanguageRules = LanguageRules {
    singular: RuleList {
        transformations: &[(r#"(?i)oj$"#, r#"o"#, "")],
        uninflected: &[""],
    },
    plural: RuleList {
        transformations: &[(r#"(?i)o$"#, r#"oj"#, "")],
        uninflected: &[""],
    },
    irregular: &[("", "")],
};

/// Italian.
pub(super) const ITALIAN: LanguageRules = LanguageRules {
    singular: RuleList {
        transformations: &[
            (r#"(?i)([aeiou])sce$"#, r#"${1}scia"#, ""),
            (r#"(?i)cie$"#, r#"cia"#, ""),
            (r#"(?i)gie$"#, r#"gia"#, ""),
            (r#"(?i)([^aeiou])ce$"#, r#"${1}cia"#, ""),
            (r#"(?i)([^aeiou])ge$"#, r#"${1}gia"#, ""),
            (
                r#"(?i)([bcdfghjklmnpqrstvwxyz][aeiou])chi$"#,
                r#"${1}co"#,
                "",
            ),
            (
                r#"(?i)([bcdfghjklmnpqrstvwxyz][aeiou])ghi$"#,
                r#"${1}go"#,
                "",
            ),
            (
                r#"(?i)([aeiou][bcdfghjklmnpqrstvwxyz])ci$"#,
                r#"${1}co"#,
                "",
            ),
            (
                r#"(?i)([aeiou][bcdfghjklmnpqrstvwxyz])gi$"#,
                r#"${1}go"#,
                "",
            ),
            (r#"(?i)([^aeiou])i$"#, r#"${1}io"#, ""),
            (r#"(?i)([^aeiou])ci$"#, r#"${1}co"#, ""),
            (r#"(?i)([^aeiou])gi$"#, r#"${1}go"#, ""),
            (r#"(?i)e$"#, r#"a"#, ""),
            (r#"(?i)i$"#, r#"e"#, ""),
            (r#"(?i)i$"#, r#"o"#, ""),
        ],
        uninflected: &[
            "alpaca",
            "auto",
            "bar",
            "blu",
            "boia",
            "boomerang",
            "brindisi",
            "campus",
            "computer",
            "crisi",
            "crocevia",
            "dopocena",
            "film",
            "foto",
            "fuchsia",
            "gnu",
            "gorilla",
            "gru",
            "iguana",
            "kamikaze",
            "karaoke",
            "koala",
            "lama",
            "menu",
            "metropoli",
            "moto",
            "opossum",
            "panda",
            "quiz",
            "radio",
            "re",
            "scacciapensieri",
            "serie",
            "smartphone",
            "sosia",
            "sottoscala",
            "specie",
            "sport",
            "tablet",
            "taxi",
            "vaglia",
            "virt\u{f9}",
            "virus",
            "yogurt",
            "foto",
            "fuchsia",
        ],
    },
    plural: RuleList {
        transformations: &[
            (r#"(?i)([aeiou])scia$"#, r#"${1}sce"#, ""),
            (r#"(?i)cia$"#, r#"cie"#, ""),
            (r#"(?i)gia$"#, r#"gie"#, ""),
            (r#"(?i)([^aeiou])cia$"#, r#"${1}ce"#, ""),
            (r#"(?i)([^aeiou])gia$"#, r#"${1}ge"#, ""),
            (
                r#"(?i)([bcdfghjklmnpqrstvwxyz][aeiou])co$"#,
                r#"${1}chi"#,
                "",
            ),
            (
                r#"(?i)([bcdfghjklmnpqrstvwxyz][aeiou])go$"#,
                r#"${1}ghi"#,
                "",
            ),
            (
                r#"(?i)([aeiou][bcdfghjklmnpqrstvwxyz])co$"#,
                r#"${1}ci"#,
                "",
            ),
            (
                r#"(?i)([aeiou][bcdfghjklmnpqrstvwxyz])go$"#,
                r#"${1}gi"#,
                "",
            ),
            (r#"(?i)([^aeiou])io$"#, r#"${1}i"#, ""),
            (r#"(?i)([aeiou])io$"#, r#"${1}i"#, ""),
            (r#"(?i)a$"#, r#"e"#, ""),
            (r#"(?i)e$"#, r#"i"#, ""),
            (r#"(?i)o$"#, r#"i"#, ""),
        ],
        uninflected: &[
            "alpaca",
            "auto",
            "bar",
            "blu",
            "boia",
            "boomerang",
            "brindisi",
            "campus",
            "computer",
            "crisi",
            "crocevia",
            "dopocena",
            "film",
            "foto",
            "fuchsia",
            "gnu",
            "gorilla",
            "gru",
            "iguana",
            "kamikaze",
            "karaoke",
            "koala",
            "lama",
            "menu",
            "metropoli",
            "moto",
            "opossum",
            "panda",
            "quiz",
            "radio",
            "re",
            "scacciapensieri",
            "serie",
            "smartphone",
            "sosia",
            "sottoscala",
            "specie",
            "sport",
            "tablet",
            "taxi",
            "vaglia",
            "virt\u{f9}",
            "virus",
            "yogurt",
            "foto",
            "fuchsia",
        ],
    },
    irregular: &[
        ("ala", "ali"),
        ("albergo", "alberghi"),
        ("amica", "amiche"),
        ("amico", "amici"),
        ("ampio", "ampi"),
        ("arancia", "arance"),
        ("arma", "armi"),
        ("asparago", "asparagi"),
        ("banca", "banche"),
        ("belga", "belgi"),
        ("braccio", "braccia"),
        ("budello", "budella"),
        ("bue", "buoi"),
        ("caccia", "cacce"),
        ("calcagno", "calcagna"),
        ("camicia", "camicie"),
        ("cane", "cani"),
        ("capitale", "capitali"),
        ("carcere", "carceri"),
        ("casa", "case"),
        ("cavaliere", "cavalieri"),
        ("centinaio", "centinaia"),
        ("cerchio", "cerchia"),
        ("cervello", "cervella"),
        ("chiave", "chiavi"),
        ("chirurgo", "chirurgi"),
        ("ciglio", "ciglia"),
        ("citt\u{e0}", "citt\u{e0}"),
        ("corno", "corna"),
        ("corpo", "corpi"),
        ("crisi", "crisi"),
        ("dente", "denti"),
        ("dio", "dei"),
        ("dito", "dita"),
        ("dottore", "dottori"),
        ("fiore", "fiori"),
        ("fratello", "fratelli"),
        ("fuoco", "fuochi"),
        ("gamba", "gambe"),
        ("ginocchio", "ginocchia"),
        ("gioco", "giochi"),
        ("giornale", "giornali"),
        ("giraffa", "giraffe"),
        ("labbro", "labbra"),
        ("lenzuolo", "lenzuola"),
        ("libro", "libri"),
        ("madre", "madri"),
        ("maestro", "maestri"),
        ("magico", "magici"),
        ("mago", "maghi"),
        ("maniaco", "maniaci"),
        ("manico", "manici"),
        ("mano", "mani"),
        ("medico", "medici"),
        ("membro", "membri"),
        ("metropoli", "metropoli"),
        ("migliaio", "migliaia"),
        ("miglio", "miglia"),
        ("mille", "mila"),
        ("mio", "miei"),
        ("moglie", "mogli"),
        ("mosaico", "mosaici"),
        ("muro", "muri"),
        ("nemico", "nemici"),
        ("nome", "nomi"),
        ("occhio", "occhi"),
        ("orecchio", "orecchi"),
        ("osso", "ossa"),
        ("paio", "paia"),
        ("pane", "pani"),
        ("papa", "papi"),
        ("pasta", "paste"),
        ("penna", "penne"),
        ("pesce", "pesci"),
        ("piede", "piedi"),
        ("pittore", "pittori"),
        ("poeta", "poeti"),
        ("porco", "porci"),
        ("porto", "porti"),
        ("problema", "problemi"),
        ("ragazzo", "ragazzi"),
        ("re", "re"),
        ("rene", "reni"),
        ("riso", "risa"),
        ("rosa", "rosa"),
        ("sale", "sali"),
        ("sarto", "sarti"),
        ("scuola", "scuole"),
        ("serie", "serie"),
        ("serramento", "serramenta"),
        ("sorella", "sorelle"),
        ("specie", "specie"),
        ("staio", "staia"),
        ("stazione", "stazioni"),
        ("strido", "strida"),
        ("strillo", "strilla"),
        ("studio", "studi"),
        ("suo", "suoi"),
        ("superficie", "superfici"),
        ("tavolo", "tavoli"),
        ("tempio", "templi"),
        ("treno", "treni"),
        ("tuo", "tuoi"),
        ("uomo", "uomini"),
        ("uovo", "uova"),
        ("urlo", "urla"),
        ("valigia", "valigie"),
        ("vestigio", "vestigia"),
        ("vino", "vini"),
        ("viola", "viola"),
        ("zio", "zii"),
    ],
};
