[workspace]
resolver = "2"
members = [
    "framework",
    "app",
    "suprnova-cli",
    "suprnova-macros",
    "crates/suprnova-web-push",
    "crates/suprnova-payments-stripe",
    "crates/suprnova-payments-paddle",
]

[workspace.package]
version = "1.2.1"
edition = "2024"
rust-version = "1.91.1"
license = "MIT"

[profile.dev]
debug = "line-tables-only"
