// This file is auto-generated by Suprnova. Do not edit manually.
// Run `suprnova generate-types` to regenerate.

import '@inertiajs/core';

export interface AppShared {
  auth: Auth;
}

export interface Auth {
  user: UserInfo | null;
}

export interface UserInfo {
  id: number;
  name: string;
  email: string;
}

export interface DashboardProps {
  stats: Stats;
  recent_notes: Array<NoteSummary>;
}

export interface Stats {
  notes: number;
  written_today: number;
}

export interface Flash {
  toast: Toast | null;
}

export interface Toast {
  kind: string;
  message: string;
}

export interface ForgotPasswordProps {
}

export interface HomeProps {
  title: string;
  message: string;
}

export interface LoginProps {
}

export interface NotesIndexProps {
  notes: Array<NoteSummary>;
  search: string;
}

export interface NoteSummary {
  id: number;
  title: string;
  created_at: string;
}

export interface NotesShowProps {
  note: NoteView;
}

export interface NoteView {
  id: number;
  title: string;
  body: string | null;
  created_at: string;
}

export interface RegisterProps {
}

export interface ResetPasswordProps {
  token: string;
}

export interface VerifyEmailProps {
  email: string;
}

export interface Pages {
  "Dashboard": DashboardProps;
  "Home": HomeProps;
  "Notes/Index": NotesIndexProps;
  "Notes/Show": NotesShowProps;
  "auth/ForgotPassword": ForgotPasswordProps;
  "auth/Login": LoginProps;
  "auth/Register": RegisterProps;
  "auth/ResetPassword": ResetPasswordProps;
  "auth/VerifyEmail": VerifyEmailProps;
}

export interface SharedProps {
  root: string;
  auth: Auth;
}

export type Errors = Record<string, string>;

export type PageProps<C extends keyof Pages> = Pages[C] & SharedProps & { errors: Errors };

declare module '@inertiajs/core' {
  export interface InertiaConfig {
    sharedPageProps: SharedProps;
    errorValueType: string;
    flashDataType: Flash;
  }
}
