// This file is auto-generated by Suprnova. Do not edit manually.
// Run `suprnova generate-types` to regenerate.

import '@inertiajs/core';

export interface DashboardProps {
  user: UserInfo;
}

export interface UserInfo {
  id: number;
  name: string;
  email: string;
}

export interface ForgotPasswordProps {
}

export interface HomeProps {
  title: string;
  message: string;
}

export interface LoginProps {
}

export interface NoteShowProps {
  note: NoteInfo;
}

export interface NoteInfo {
  id: number;
  title: string;
  body: string | null;
  created_at: string;
}

export interface RegisterProps {
}

export interface ResetPasswordProps {
  token: string;
}

export interface Toast {
  kind: unknown;
  message: string;
}

export interface VerifyEmailProps {
  email: string;
}

export interface Pages {
  "Dashboard": DashboardProps;
  "Home": HomeProps;
  "Notes/Show": NoteShowProps;
  "auth/ForgotPassword": ForgotPasswordProps;
  "auth/Login": LoginProps;
  "auth/Register": RegisterProps;
  "auth/ResetPassword": ResetPasswordProps;
  "auth/VerifyEmail": VerifyEmailProps;
}

export interface SharedProps {
  root: string;
}

export type Errors = Record<string, string>;

export type PageProps<C extends keyof Pages> = Pages[C] & SharedProps & { errors: Errors };

declare module '@inertiajs/core' {
  export interface InertiaConfig {
    sharedPageProps: SharedProps;
    errorValueType: string;
    flashDataType: Toast;
  }
}
