//! Injectable server-side instance identity generation.

use std::error::Error;
use std::fmt;

use crate::identity::InstanceId;

/// Closed failure reason for server identity generation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RandomErrorKind {
    /// The operating-system random source was unavailable.
    SourceUnavailable,
    /// Generated bytes could not satisfy the fixed identity contract.
    InvalidGeneratedIdentity,
}

impl RandomErrorKind {
    /// Returns the stable safe machine value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::SourceUnavailable => "random_source_unavailable",
            Self::InvalidGeneratedIdentity => "invalid_generated_identity",
        }
    }
}

/// Redacted server identity-generation failure.
#[derive(Clone, Copy, Eq, PartialEq)]
pub struct RandomError {
    kind: RandomErrorKind,
}

impl RandomError {
    const fn new(kind: RandomErrorKind) -> Self {
        Self { kind }
    }

    /// Creates a closed failure for a custom generator that returned unusable bytes.
    #[must_use]
    pub const fn generation_failed() -> Self {
        Self::new(RandomErrorKind::InvalidGeneratedIdentity)
    }

    /// Returns the closed failure reason.
    #[must_use]
    pub const fn kind(self) -> RandomErrorKind {
        self.kind
    }
}

impl fmt::Display for RandomError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.kind.as_str())
    }
}

impl fmt::Debug for RandomError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Display::fmt(self, formatter)
    }
}

impl Error for RandomError {}

/// Produces opaque server authority; browser nonces never implement this role.
pub trait InstanceIdGenerator: Send + Sync {
    /// Generates at least 128 bits of server-controlled instance identity.
    fn generate(&self) -> Result<InstanceId, RandomError>;
}

/// Production instance generator backed by the operating-system random source.
#[derive(Clone, Copy, Debug, Default)]
pub struct SystemInstanceIdGenerator;

impl InstanceIdGenerator for SystemInstanceIdGenerator {
    fn generate(&self) -> Result<InstanceId, RandomError> {
        let mut bytes = [0_u8; 16];
        getrandom::fill(&mut bytes)
            .map_err(|_| RandomError::new(RandomErrorKind::SourceUnavailable))?;
        InstanceId::from_bytes(&bytes)
            .map_err(|_| RandomError::new(RandomErrorKind::InvalidGeneratedIdentity))
    }
}
