// @generated by scripts/generate-browser-contracts.mjs from fixtures/v4/directive-grammar.json.
// Do not edit by hand; run the generator instead.

#![allow(missing_docs, reason = "generated from the reviewed directive fixture")]

/// Reviewed v4 fixture-manifest identity used to generate this contract.
pub const DIRECTIVE_FIXTURE_MANIFEST_SHA256: &str =
    "75d79b697968645501a48d0cd961f8f757d1775c8688a9da1915cecdf52a0252";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DirectiveOwner {
    Island,
    KeyedScope,
    Element,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DirectiveValue {
    Empty,
    Identifier,
    Literal,
    Field,
    Action,
    Target,
    Mapping,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DirectivePhase {
    Local,
    Schedule,
    Feedback,
    Morph,
    Navigation,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DirectiveFallback {
    Inert,
    Native,
    RetainDom,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DirectiveContract {
    pub name: &'static str,
    pub owner: DirectiveOwner,
    pub value: DirectiveValue,
    pub modifiers: &'static [&'static str],
    pub roles: &'static [&'static str],
    pub conflicts: &'static [&'static str],
    pub phase: DirectivePhase,
    pub fallback: DirectiveFallback,
    pub capability: Option<&'static str>,
}

#[rustfmt::skip]
pub const DIRECTIVE_CONTRACTS: &[DirectiveContract] = &[
    DirectiveContract { name: "click", owner: DirectiveOwner::Element, value: DirectiveValue::Action, modifiers: &["prevent", "stop", "once", "self", "trusted", "capture"], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "submit", owner: DirectiveOwner::Element, value: DirectiveValue::Action, modifiers: &["prevent", "stop", "once", "self", "trusted", "capture"], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "change", owner: DirectiveOwner::Element, value: DirectiveValue::Action, modifiers: &["prevent", "stop", "once", "self", "trusted", "capture"], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "input", owner: DirectiveOwner::Element, value: DirectiveValue::Action, modifiers: &["prevent", "stop", "once", "self", "trusted", "capture"], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "keydown", owner: DirectiveOwner::Element, value: DirectiveValue::Action, modifiers: &["prevent", "stop", "once", "self", "trusted", "capture", "enter", "escape", "space", "tab", "up", "down", "left", "right"], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "init", owner: DirectiveOwner::Element, value: DirectiveValue::Action, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "model", owner: DirectiveOwner::Element, value: DirectiveValue::Field, modifiers: &["immediate", "change", "blur", "action", "submit", "debounce.100ms", "debounce.250ms", "debounce.500ms", "throttle.100ms", "throttle.250ms", "latest", "serial", "parallel"], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "url", owner: DirectiveOwner::Island, value: DirectiveValue::Field, modifiers: &["reflect", "navigate"], roles: &[], conflicts: &["navigate"], phase: DirectivePhase::Navigation, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "signal", owner: DirectiveOwner::KeyedScope, value: DirectiveValue::Mapping, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "toggle", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "show", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "class", owner: DirectiveOwner::Element, value: DirectiveValue::Mapping, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "attr", owner: DirectiveOwner::Element, value: DirectiveValue::Mapping, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "selected", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "expanded", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "inert", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "focus", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "idle", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "dirty", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "queued", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "loading", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "validating", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "success", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "interrupted", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "offline", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "retrying", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "error", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &["show", "hide", "class", "disabled", "busy", "live.polite", "live.assertive"], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "effect", owner: DirectiveOwner::Island, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "on", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &["prevent", "stop", "once", "self", "trusted", "capture", "enter", "escape", "space", "tab", "up", "down", "left", "right"], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "call", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Local, fallback: DirectiveFallback::Inert, capability: None },
    DirectiveContract { name: "component", owner: DirectiveOwner::Island, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Morph, fallback: DirectiveFallback::RetainDom, capability: None },
    DirectiveContract { name: "key", owner: DirectiveOwner::KeyedScope, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Morph, fallback: DirectiveFallback::RetainDom, capability: None },
    DirectiveContract { name: "lazy", owner: DirectiveOwner::Island, value: DirectiveValue::Empty, modifiers: &["visible", "eager"], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "preserve", owner: DirectiveOwner::Element, value: DirectiveValue::Empty, modifiers: &["self", "children", "subtree"], roles: &[], conflicts: &["ignore", "replace"], phase: DirectivePhase::Morph, fallback: DirectiveFallback::RetainDom, capability: None },
    DirectiveContract { name: "ignore", owner: DirectiveOwner::Element, value: DirectiveValue::Empty, modifiers: &["self", "children", "subtree"], roles: &[], conflicts: &["preserve", "replace"], phase: DirectivePhase::Morph, fallback: DirectiveFallback::RetainDom, capability: None },
    DirectiveContract { name: "replace", owner: DirectiveOwner::Element, value: DirectiveValue::Empty, modifiers: &["self", "children", "subtree"], roles: &[], conflicts: &["preserve", "ignore"], phase: DirectivePhase::Morph, fallback: DirectiveFallback::RetainDom, capability: None },
    DirectiveContract { name: "persist", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Morph, fallback: DirectiveFallback::RetainDom, capability: None },
    DirectiveContract { name: "teleport", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Morph, fallback: DirectiveFallback::RetainDom, capability: None },
    DirectiveContract { name: "transition", owner: DirectiveOwner::Element, value: DirectiveValue::Identifier, modifiers: &["enter", "leave", "both", "reduced-motion"], roles: &[], conflicts: &[], phase: DirectivePhase::Morph, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "navigate", owner: DirectiveOwner::Element, value: DirectiveValue::Empty, modifiers: &["replace", "transition", "hover", "visible", "eager"], roles: &[], conflicts: &["url"], phase: DirectivePhase::Navigation, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "prefetch", owner: DirectiveOwner::Element, value: DirectiveValue::Empty, modifiers: &["replace", "transition", "hover", "visible", "eager"], roles: &[], conflicts: &[], phase: DirectivePhase::Navigation, fallback: DirectiveFallback::Native, capability: None },
    DirectiveContract { name: "upload", owner: DirectiveOwner::Element, value: DirectiveValue::Field, modifiers: &[], roles: &["cancel", "retry", "remove"], conflicts: &["model"], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Native, capability: Some("uploads@1") },
    DirectiveContract { name: "progress", owner: DirectiveOwner::Element, value: DirectiveValue::Target, modifiers: &[], roles: &[], conflicts: &[], phase: DirectivePhase::Feedback, fallback: DirectiveFallback::Inert, capability: Some("uploads@1") },
    DirectiveContract { name: "poll", owner: DirectiveOwner::Island, value: DirectiveValue::Action, modifiers: &["immediate", "visible", "always", "5s", "15s", "30s", "60s"], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Inert, capability: Some("async@1") },
    DirectiveContract { name: "stream", owner: DirectiveOwner::Island, value: DirectiveValue::Identifier, modifiers: &["push-only", "hybrid"], roles: &[], conflicts: &[], phase: DirectivePhase::Schedule, fallback: DirectiveFallback::Inert, capability: Some("async@1") },
];

#[rustfmt::skip]
pub const RESERVED_DIRECTIVES: &[&str] = &[];
#[rustfmt::skip]
pub const DIRECTIVE_TARGET_KINDS: &[&str] = &["island", "keyed_scope", "element"];
#[rustfmt::skip]
pub const DIRECTIVE_LITERAL_KINDS: &[&str] = &["boolean", "integer", "string", "token", "mapping"];
#[rustfmt::skip]
pub const DIRECTIVE_ARGUMENT_FORMS: &[&str] = &["none", "identifier", "field", "action", "target", "mapping"];
#[rustfmt::skip]
pub const DIRECTIVE_FALLBACKS: &[&str] = &["inert", "native", "retain_dom"];

#[must_use]
pub fn directive_contract(name: &str) -> Option<&'static DirectiveContract> {
    DIRECTIVE_CONTRACTS
        .iter()
        .find(|contract| contract.name == name)
}

#[must_use]
pub fn is_reserved_directive(name: &str) -> bool {
    RESERVED_DIRECTIVES.contains(&name)
}
