//! Shared setup for the `laravel_database` tests: one database per test on
//! the engine it names, loaded with the Laravel 13 fixture for that engine
//! when the test needs Laravel's tables.
//!
//! SQLite tests get a file of their own and run with the ordinary suite.
//! The Postgres and MySQL tests are ignored until `PG_TEST_URL` and
//! `MYSQL_TEST_URL` name a throwaway database, which
//! `scripts/check-laravel-database.sh` creates; every such test empties
//! that database before it starts, and `.config/nextest.toml` runs the tests
//! of one engine one at a time.

use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Duration;

use sea_orm::{ConnectOptions, ConnectionTrait, Database, DatabaseConnection, DbBackend};
use serde::Deserialize;

/// The engine a test runs on.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Engine {
    Sqlite,
    Postgres,
    Mysql,
}

impl Engine {
    /// The fixture file's engine name.
    pub fn fixture_name(self) -> &'static str {
        match self {
            Engine::Sqlite => "sqlite",
            Engine::Postgres => "pgsql",
            Engine::Mysql => "mysql",
        }
    }

    pub fn backend(self) -> DbBackend {
        match self {
            Engine::Sqlite => DbBackend::Sqlite,
            Engine::Postgres => DbBackend::Postgres,
            Engine::Mysql => DbBackend::MySql,
        }
    }
}

/// Three tests from one case: SQLite with the suite, Postgres and MySQL
/// when their throwaway database is named. Each runs serially within its
/// process, since the framework's registries are process-wide.
#[macro_export]
macro_rules! on_every_engine {
    ($case:path => $sqlite:ident, $postgres:ident, $mysql:ident) => {
        #[tokio::test]
        #[serial_test::serial]
        async fn $sqlite() {
            $case($crate::support::Engine::Sqlite).await
        }

        #[tokio::test]
        #[serial_test::serial]
        #[ignore = "requires a throwaway Postgres at PG_TEST_URL"]
        async fn $postgres() {
            $case($crate::support::Engine::Postgres).await
        }

        #[tokio::test]
        #[serial_test::serial]
        #[ignore = "requires a throwaway MySQL at MYSQL_TEST_URL"]
        async fn $mysql() {
            $case($crate::support::Engine::Mysql).await
        }
    };
}

/// The committed Laravel 13 fixture for one engine, generated by
/// `fixtures/generate.sh`.
#[derive(Debug, Clone, Deserialize)]
pub struct Fixture {
    pub schema: Vec<String>,
    pub rows: Vec<String>,
    pub users: std::collections::BTreeMap<String, FixtureUser>,
    pub sessions: FixtureSessions,
    pub morph: FixtureMorph,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FixtureUser {
    pub id: u64,
    pub password: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FixtureSessions {
    pub user: String,
    pub guest: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct FixtureMorph {
    pub class: String,
    pub alias: String,
}

pub fn fixture(engine: Engine) -> Fixture {
    let path = fixtures_dir().join(format!("laravel-13-{}.json", engine.fixture_name()));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read the fixture {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

pub fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/laravel_database/fixtures")
}

/// One test's database. A SQLite file is removed when this is dropped.
pub struct Db {
    pub conn: DatabaseConnection,
    pub engine: Engine,
    sqlite_file: Option<PathBuf>,
}

impl Drop for Db {
    fn drop(&mut self) {
        if let Some(path) = self.sqlite_file.take() {
            for suffix in ["", "-wal", "-shm", "-journal"] {
                let _ = std::fs::remove_file(format!("{}{suffix}", path.display()));
            }
        }
    }
}

impl Db {
    /// The SQLite file this database lives in, for a child process.
    pub fn sqlite_path(&self) -> Option<&std::path::Path> {
        self.sqlite_file.as_deref()
    }
}

static SQLITE_FILES: AtomicU64 = AtomicU64::new(0);

/// An empty database on `engine`.
pub async fn empty(engine: Engine) -> Db {
    match engine {
        Engine::Sqlite => {
            let n = SQLITE_FILES.fetch_add(1, Ordering::Relaxed);
            let path = std::env::temp_dir().join(format!(
                "suprnova-ldb-{}-{n}-{}.sqlite",
                std::process::id(),
                uuid::Uuid::new_v4().simple()
            ));
            let conn = connect(&format!("sqlite://{}?mode=rwc", path.display())).await;
            conn.execute_unprepared("PRAGMA foreign_keys = ON")
                .await
                .expect("enable foreign keys");
            Db {
                conn,
                engine,
                sqlite_file: Some(path),
            }
        }
        Engine::Postgres => {
            let url = std::env::var("PG_TEST_URL")
                .expect("set PG_TEST_URL to a throwaway Postgres database");
            let conn = connect(&url).await;
            conn.execute_unprepared("DROP SCHEMA IF EXISTS public CASCADE")
                .await
                .expect("drop the public schema");
            conn.execute_unprepared("CREATE SCHEMA public")
                .await
                .expect("create the public schema");
            Db {
                conn,
                engine,
                sqlite_file: None,
            }
        }
        Engine::Mysql => {
            let url = std::env::var("MYSQL_TEST_URL")
                .expect("set MYSQL_TEST_URL to a throwaway MySQL database");
            let name = url
                .rsplit('/')
                .next()
                .and_then(|tail| tail.split('?').next())
                .filter(|name| !name.is_empty())
                .expect("MYSQL_TEST_URL names a database")
                .to_owned();
            assert!(
                name.starts_with("suprnova_test_"),
                "MYSQL_TEST_URL must name a throwaway suprnova_test_* database, not {name}"
            );
            let conn = connect(&url).await;
            // Drop every table on one pinned connection, with foreign key
            // checks off for that session, so the order does not matter.
            let tables: Vec<String> = conn
                .query_all_raw(sea_orm::Statement::from_string(
                    DbBackend::MySql,
                    "SELECT TABLE_NAME AS name FROM information_schema.TABLES \
                     WHERE TABLE_SCHEMA = DATABASE()"
                        .to_owned(),
                ))
                .await
                .expect("list the test database's tables")
                .iter()
                .map(|row| row.try_get::<String>("", "name").expect("a table name"))
                .collect();
            if !tables.is_empty() {
                use sea_orm::TransactionTrait;
                let pinned = conn.begin().await.expect("pin a connection");
                pinned
                    .execute_unprepared("SET FOREIGN_KEY_CHECKS = 0")
                    .await
                    .expect("foreign key checks off");
                let list = tables
                    .iter()
                    .map(|t| format!("`{t}`"))
                    .collect::<Vec<_>>()
                    .join(", ");
                pinned
                    .execute_unprepared(&format!("DROP TABLE IF EXISTS {list}"))
                    .await
                    .expect("drop the test database's tables");
                pinned
                    .execute_unprepared("SET FOREIGN_KEY_CHECKS = 1")
                    .await
                    .expect("foreign key checks on");
                pinned.commit().await.expect("release the connection");
            }
            Db {
                conn,
                engine,
                sqlite_file: None,
            }
        }
    }
}

async fn connect(url: &str) -> DatabaseConnection {
    let mut options = ConnectOptions::new(url.to_owned());
    options
        .max_connections(4)
        .min_connections(0)
        .connect_timeout(Duration::from_secs(10))
        .acquire_timeout(Duration::from_secs(30))
        .sqlx_logging(false);
    Database::connect(options)
        .await
        .unwrap_or_else(|e| panic!("connect to the test database: {e}"))
}

/// A database holding the Laravel 13 schema and the rows Laravel wrote.
pub async fn laravel(engine: Engine) -> (Db, Fixture) {
    let db = empty(engine).await;
    let fixture = fixture(engine);
    run_all(&db.conn, &fixture.schema).await;
    run_all(&db.conn, &fixture.rows).await;
    (db, fixture)
}

/// A database holding the Laravel 13 schema and no rows.
pub async fn laravel_schema(engine: Engine) -> (Db, Fixture) {
    let db = empty(engine).await;
    let fixture = fixture(engine);
    run_all(&db.conn, &fixture.schema).await;
    (db, fixture)
}

async fn run_all(conn: &DatabaseConnection, statements: &[String]) {
    for statement in statements {
        conn.execute_unprepared(statement)
            .await
            .unwrap_or_else(|e| panic!("fixture statement failed: {e}\n{statement}"));
    }
}

/// Make `conn` the connection `DB::connection()` and the models resolve,
/// for as long as the returned guard lives.
pub fn bind(conn: &DatabaseConnection) -> suprnova::testing::TestContainerGuard {
    let guard = suprnova::testing::TestContainer::fake();
    suprnova::testing::TestContainer::singleton(suprnova::DbConnection::from_raw(conn.clone()));
    guard
}

/// What PHP 8.4 makes of a password hash: `password_get_info`'s
/// `algoName`, and `password_verify` of `password` against it. The
/// mechanism allows the host `php` for this check and no other.
pub fn php_password(hash: &str, password: &str) -> (String, bool) {
    use std::io::Write;
    use std::process::{Command, Stdio};
    let script = r#"$in = json_decode(stream_get_contents(STDIN), true);
echo json_encode(["algo" => password_get_info($in["hash"])["algoName"],
                  "ok" => password_verify($in["password"], $in["hash"])]);"#;
    let mut child = Command::new("php")
        .arg("-r")
        .arg(script)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("run php: the laravel-database mechanism needs php 8.4 on PATH");
    let input = serde_json::json!({ "hash": hash, "password": password }).to_string();
    child
        .stdin
        .take()
        .expect("php stdin")
        .write_all(input.as_bytes())
        .expect("write to php");
    let output = child.wait_with_output().expect("wait for php");
    assert!(
        output.status.success(),
        "php failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let answer: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("php printed JSON");
    (
        answer["algo"].as_str().unwrap_or_default().to_owned(),
        answer["ok"].as_bool().unwrap_or(false),
    )
}

/// The rows a query returns, each as a JSON object keyed by column, read
/// through text so no column type stands between the test and the value.
pub async fn rows(conn: &DatabaseConnection, sql: &str) -> Vec<serde_json::Value> {
    let backend = conn.get_database_backend();
    let rows = conn
        .query_all_raw(sea_orm::Statement::from_string(backend, sql.to_owned()))
        .await
        .unwrap_or_else(|e| panic!("query failed: {e}\n{sql}"));
    rows.iter().map(row_json).collect()
}

/// One row as JSON, every column read as the widest type that decodes.
pub fn row_json(row: &sea_orm::QueryResult) -> serde_json::Value {
    let mut object = serde_json::Map::new();
    for name in row.column_names() {
        let value = if let Ok(v) = row.try_get::<Option<i64>>("", &name) {
            serde_json::json!(v)
        } else if let Ok(v) = row.try_get::<Option<u64>>("", &name) {
            serde_json::json!(v)
        } else if let Ok(v) = row.try_get::<Option<i32>>("", &name) {
            serde_json::json!(v)
        } else if let Ok(v) = row.try_get::<Option<u32>>("", &name) {
            serde_json::json!(v)
        } else if let Ok(v) = row.try_get::<Option<i16>>("", &name) {
            serde_json::json!(v)
        } else if let Ok(v) = row.try_get::<Option<u16>>("", &name) {
            serde_json::json!(v)
        } else if let Ok(v) = row.try_get::<Option<String>>("", &name) {
            serde_json::json!(v)
        } else if let Ok(v) = row.try_get::<Option<uuid::Uuid>>("", &name) {
            serde_json::json!(v.map(|v| v.to_string()))
        } else if let Ok(v) = row.try_get::<Option<chrono::NaiveDateTime>>("", &name) {
            serde_json::json!(v.map(|v| v.format("%Y-%m-%d %H:%M:%S").to_string()))
        } else if let Ok(v) = row.try_get::<Option<chrono::DateTime<chrono::Utc>>>("", &name) {
            serde_json::json!(v.map(|v| v.format("%Y-%m-%d %H:%M:%S").to_string()))
        } else if let Ok(v) = row.try_get::<Option<f64>>("", &name) {
            serde_json::json!(v)
        } else if let Ok(v) = row.try_get::<Option<bool>>("", &name) {
            serde_json::json!(v)
        } else if let Ok(v) = row.try_get::<Option<serde_json::Value>>("", &name) {
            v.unwrap_or(serde_json::Value::Null)
        } else {
            panic!("column {name} decodes as none of the test's types")
        };
        object.insert(name, value);
    }
    serde_json::Value::Object(object)
}

/// A string field of a [`rows`] row.
pub fn text(row: &serde_json::Value, column: &str) -> String {
    match &row[column] {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Number(n) => n.to_string(),
        other => panic!("column {column} is {other}, not text"),
    }
}

/// An integer field of a [`rows`] row.
pub fn int(row: &serde_json::Value, column: &str) -> i64 {
    match &row[column] {
        serde_json::Value::Number(n) => n.as_i64().expect("an integer"),
        serde_json::Value::String(s) => s.parse().expect("an integer"),
        other => panic!("column {column} is {other}, not an integer"),
    }
}

/// `SELECT COUNT(*) FROM table [WHERE where]`.
pub async fn count(conn: &DatabaseConnection, table: &str, filter: &str) -> i64 {
    let filter = if filter.is_empty() {
        String::new()
    } else {
        format!(" WHERE {filter}")
    };
    let row = conn
        .query_one_raw(sea_orm::Statement::from_string(
            conn.get_database_backend(),
            format!("SELECT COUNT(*) AS n FROM {table}{filter}"),
        ))
        .await
        .expect("count")
        .expect("a count row");
    row.try_get::<i64>("", "n").expect("count as i64")
}

/// A notification for the database channel.
#[derive(serde::Serialize, serde::Deserialize)]
pub struct Shipped;

impl suprnova::notifications::Notification for Shipped {
    fn notification_name() -> &'static str {
        "Shipped"
    }

    fn channels(&self) -> Vec<&'static str> {
        vec!["database"]
    }

    fn data(&self) -> serde_json::Value {
        serde_json::json!({ "order": 7 })
    }
}

/// Turns `LaravelDatabase::share` on for as long as it lives, and back to
/// the environment's answer when dropped.
pub struct Shared;

impl Shared {
    pub fn on() -> Self {
        suprnova::LaravelDatabase::share(true);
        Self
    }
}

impl Drop for Shared {
    fn drop(&mut self) {
        suprnova::LaravelDatabase::follow_environment();
    }
}

/// Install a Crypt key, an auth manager whose `users` provider is the
/// scaffold's `User` model, and the default rate limiter, inside the
/// caller's container scope (see [`bind`]).
pub async fn install_scaffold_auth() {
    let _ = suprnova::crypto::_test_install_key(suprnova::EncryptionKey::generate());
    suprnova::testing::TestContainer::singleton(suprnova::AuthManager::new(
        suprnova::AuthConfig::default(),
    ));
    suprnova::Auth::register_provider(
        "users",
        std::sync::Arc::new(suprnova::EloquentUserProvider::<crate::scaffold::user::User>::new()),
    )
    .expect("register the users provider");
    suprnova::rate_limit::bootstrap_default().await;
}

/// Run `fut` as one request would: with a session and the request's auth
/// state in scope.
pub async fn in_request<F, T>(fut: F) -> T
where
    F: std::future::Future<Output = T>,
{
    let session_slot = suprnova::session::new_session_slot_for_test();
    let pending_slot = suprnova::session::new_pending_cookies_slot_for_test();
    suprnova::session::session_scope_for_test(
        session_slot,
        suprnova::session::pending_cookies_scope_for_test(
            pending_slot,
            suprnova::auth::request_state::request_state_scope_for_test(fut),
        ),
    )
    .await
}

/// The stored password hash of the user with `email` in `users`.
pub async fn stored_hash(conn: &DatabaseConnection, email: &str) -> String {
    let rows = rows(
        conn,
        &format!("SELECT password FROM users WHERE email = '{email}'"),
    )
    .await;
    text(&rows[0], "password")
}

/// Run `body` in a child process of this test binary, alone: the
/// Magnetar engine installs once per process, and libtest runs several
/// tests in one. `name` is the calling test's full path; the child runs
/// that test, which finds itself the child and runs `body`.
pub fn alone<F, Fut>(name: &str, body: F)
where
    F: FnOnce() -> Fut,
    Fut: std::future::Future<Output = ()>,
{
    const ALONE: &str = "LDB_ALONE";
    if std::env::var(ALONE).as_deref() == Ok(name) {
        let runtime = tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .expect("a runtime for the child");
        runtime.block_on(body());
        return;
    }
    let output = std::process::Command::new(std::env::current_exe().expect("the test binary"))
        .args(["--exact", name, "--nocapture", "--include-ignored"])
        .env(ALONE, name)
        .output()
        .expect("run the child");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        output.status.success() && stdout.contains("1 passed"),
        "the child running {name} failed:\n{stdout}\n{stderr}"
    );
}
