"""The nested-lockfile half of scripts/bump-workspace-version.py.

Every workspace below the root resolves on its own and pins by path, in a
lockfile of its own, the first-party crates it depends on. A release that
bumps the manifests and refreshes only the root `Cargo.lock` leaves those
lockfiles at the previous version, and `cargo metadata --locked` refuses
the release commit. These tests pin the rewrite and the discovery that
keep them in step.
"""

import importlib.util
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


_LOCAL_ROOT = Path(__file__).resolve().parents[2]


def _load_bumper():
    module_path = _LOCAL_ROOT / "scripts" / "bump-workspace-version.py"
    spec = importlib.util.spec_from_file_location(
        "bump_workspace_version", module_path
    )
    if spec is None or spec.loader is None:  # pragma: no cover
        raise RuntimeError("failed to load the version bumper")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


bumper = _load_bumper()

#: The root workspace's members, as far as these tests are concerned.
MEMBERS = frozenset({"suprnova", "suprnova-live"})

#: A nested lockfile carrying every case the rewrite has to tell apart: a
#: registry crate, a registry crate that happens to share a first-party
#: name, a first-party crate resolved by path, and the nested workspace's
#: own member, which is also resolved by path but is not first-party.
LOCKFILE = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"

[[package]]
name = "suprnova"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"

[[package]]
name = "suprnova-live"
version = "1.3.7"
dependencies = [
 "serde",
]

[[package]]
name = "suprnova-live-fuzz"
version = "0.0.0"
dependencies = [
 "suprnova-live",
]
"""


class ReplaceLockfileVersionsTests(unittest.TestCase):
    def test_a_first_party_path_package_takes_the_release_version(self) -> None:
        observed = bumper.replace_lockfile_versions(LOCKFILE, MEMBERS, "2.0.0")
        expected = LOCKFILE.replace(
            'name = "suprnova-live"\nversion = "1.3.7"\n',
            'name = "suprnova-live"\nversion = "2.0.0"\n',
        )
        # Byte for byte: exactly one line moves, and it is the one
        # `cargo metadata --offline` would move.
        self.assertEqual(observed, expected)

    def test_a_registry_crate_sharing_a_first_party_name_keeps_its_version(
        self,
    ) -> None:
        observed = bumper.replace_lockfile_versions(LOCKFILE, MEMBERS, "2.0.0")
        self.assertIn('name = "suprnova"\nversion = "0.1.0"\nsource', observed)

    def test_a_nested_workspaces_own_member_keeps_its_version(self) -> None:
        observed = bumper.replace_lockfile_versions(LOCKFILE, MEMBERS, "2.0.0")
        self.assertIn('name = "suprnova-live-fuzz"\nversion = "0.0.0"\n', observed)

    def test_the_rewrite_is_idempotent_at_the_release_version(self) -> None:
        once = bumper.replace_lockfile_versions(LOCKFILE, MEMBERS, "2.0.0")
        self.assertEqual(
            bumper.replace_lockfile_versions(once, MEMBERS, "2.0.0"), once
        )

    def test_a_lockfile_naming_no_first_party_crate_is_returned_unchanged(
        self,
    ) -> None:
        self.assertEqual(
            bumper.replace_lockfile_versions(LOCKFILE, frozenset({"absent"}), "2.0.0"),
            LOCKFILE,
        )


class NestedLockfilesTests(unittest.TestCase):
    def setUp(self) -> None:
        self.root = Path(tempfile.mkdtemp()).resolve()
        self.addCleanup(lambda: shutil.rmtree(self.root, ignore_errors=True))

    def _lockfile(self, relative: str) -> Path:
        path = self.root / relative / "Cargo.lock"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("version = 4\n", encoding="utf-8")
        return path

    def test_the_root_and_build_or_vendored_trees_are_never_nested_workspaces(
        self,
    ) -> None:
        self._lockfile(".")
        fuzz = self._lockfile("crates/engine/fuzz")
        probe = self._lockfile("framework/tests/fixtures/probe")
        self._lockfile("target/package/suprnova-1.3.7")
        self._lockfile("browser/node_modules/some-package")
        self._lockfile("reference/upstream-0.1.0")

        self.assertEqual(bumper.nested_lockfiles(self.root), sorted([fuzz, probe]))

    def test_a_lockfile_git_ignores_never_ships_and_is_not_rewritten(self) -> None:
        subprocess.run(
            ["git", "init", "--quiet", str(self.root)],
            check=True,
            capture_output=True,
        )
        (self.root / ".gitignore").write_text("scratch/\n", encoding="utf-8")
        shipped = self._lockfile("crates/engine/fuzz")
        self._lockfile("scratch/clone")

        self.assertEqual(bumper.nested_lockfiles(self.root), [shipped])


if __name__ == "__main__":
    unittest.main()
