// This file is auto-generated by Suprnova. Do not edit manually.
// Run `suprnova generate-types` to regenerate.

import '@inertiajs/core';

export interface HomeProps {
  title: string;
  message: string;
}

export interface PublicUserProps {
  id: number;
  name: string;
}

export interface Stats {
  visits: number;
  likes: number;
}

export interface User {
  name: string;
  email: string;
}

export interface UserDetailProps {
  id: number;
  name: string;
  bio: string | null;
}

export interface UserProps {
  id: number;
  email: string;
  name: string;
}

export interface UserResource {
  id: number;
  email: string;
  created_at: string;
}

export interface UserResourceInput {
  id: number;
  email: string;
  created_at: string;
  password: string;
}

export interface Pages {
}

export interface SharedProps {
  root: string;
}

export type Errors = Record<string, string>;

export type PageProps<C extends keyof Pages> = Pages[C] & SharedProps & { errors: Errors };

declare module '@inertiajs/core' {
  export interface InertiaConfig {
    sharedPageProps: SharedProps;
    errorValueType: string;
  }
}
