//! Authorized idempotent durable finalization with explicit reconciliation.

use std::fmt;
use std::fmt::Write as _;
use std::sync::Arc;

use sha2::{Digest, Sha256};

use crate::action::AuthorizedAction;
use crate::host::TrustedLiveRequestContext;
use crate::identity::{ActionName, ContentDigest, ModelField, UnixMillis};

use super::{
    TransitionDisposition, UploadControlKind, UploadError, UploadErrorKind, UploadFieldPolicy,
    UploadFuture, UploadHandle, UploadIdempotencyKey, UploadRevision, UploadService, UploadState,
    UploadTransition, UploadTransitionRequest, UploadValidationStore, ValidatedUpload,
};

const MAX_FINALIZE_IDENTITY_BYTES: usize = 128;

/// Opaque idempotent host operation identity for prepared durable work.
#[derive(Clone, Eq, Hash, PartialEq)]
pub struct FinalizeToken(String);

impl FinalizeToken {
    /// Parses a bounded safe host operation identity.
    pub fn parse(value: &str) -> Result<Self, UploadError> {
        parse_finalize_identity(value).map(Self)
    }

    /// Returns the trusted operation identity for host persistence lookup.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for FinalizeToken {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("<FinalizeToken>")
    }
}

/// Opaque durable application/storage identity, never a browser path claim.
#[derive(Clone, Eq, Hash, PartialEq)]
pub struct DurableUploadId(String);

impl DurableUploadId {
    /// Parses a bounded safe durable identity generated by trusted policy.
    pub fn parse(value: &str) -> Result<Self, UploadError> {
        parse_finalize_identity(value).map(Self)
    }

    /// Returns the trusted durable identity.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for DurableUploadId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("<DurableUploadId>")
    }
}

/// Borrowed trusted request supplied to the durable finalizer capability.
#[derive(Clone, Copy)]
pub struct FinalizeRequest<'a> {
    evidence: &'a ValidatedUpload,
    action: &'a ActionName,
    idempotency_key: &'a UploadIdempotencyKey,
    requested_at: UnixMillis,
}

impl<'a> FinalizeRequest<'a> {
    const fn new(
        evidence: &'a ValidatedUpload,
        action: &'a ActionName,
        idempotency_key: &'a UploadIdempotencyKey,
        requested_at: UnixMillis,
    ) -> Self {
        Self {
            evidence,
            action,
            idempotency_key,
            requested_at,
        }
    }

    /// Returns immutable authoritative validation evidence.
    #[must_use]
    pub const fn evidence(&self) -> &ValidatedUpload {
        self.evidence
    }

    /// Returns the registered action whose invocation authorized finalization.
    #[must_use]
    pub const fn action(&self) -> &ActionName {
        self.action
    }

    /// Returns the logical finalization retry identity.
    #[must_use]
    pub const fn idempotency_key(&self) -> &UploadIdempotencyKey {
        self.idempotency_key
    }

    /// Returns the authoritative request instant.
    #[must_use]
    pub const fn requested_at(&self) -> UnixMillis {
        self.requested_at
    }
}

impl fmt::Debug for FinalizeRequest<'_> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("<FinalizeRequest:redacted>")
    }
}

/// Host-confirmed preparation for one exact logical finalization.
#[derive(Clone, Eq, PartialEq)]
pub struct PreparedFinalize {
    token: FinalizeToken,
    handle: UploadHandle,
    action: ActionName,
    idempotency_key: UploadIdempotencyKey,
    policy_digest: ContentDigest,
}

impl PreparedFinalize {
    /// Binds a host operation token to the exact engine request.
    #[must_use]
    pub fn new(request: &FinalizeRequest<'_>, token: FinalizeToken) -> Self {
        Self {
            token,
            handle: request.evidence().handle().clone(),
            action: request.action().clone(),
            idempotency_key: request.idempotency_key().clone(),
            policy_digest: request.evidence().policy_digest().clone(),
        }
    }

    /// Returns the host operation identity.
    #[must_use]
    pub const fn token(&self) -> &FinalizeToken {
        &self.token
    }

    /// Returns the temporary upload identity.
    #[must_use]
    pub const fn handle(&self) -> &UploadHandle {
        &self.handle
    }

    fn matches(&self, request: &FinalizeRequest<'_>) -> bool {
        self.handle == *request.evidence().handle()
            && self.action == *request.action()
            && self.idempotency_key == *request.idempotency_key()
            && self.policy_digest == *request.evidence().policy_digest()
    }
}

impl fmt::Debug for PreparedFinalize {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("<PreparedFinalize:redacted>")
    }
}

/// Durable logical upload outcome persisted by the host finalizer.
#[derive(Clone, Eq, PartialEq)]
pub struct DurableUpload {
    id: DurableUploadId,
    handle: UploadHandle,
    action: ActionName,
    idempotency_key: UploadIdempotencyKey,
    policy_digest: ContentDigest,
}

impl DurableUpload {
    /// Binds a trusted durable identity to one prepared finalization.
    #[must_use]
    pub fn new(prepared: &PreparedFinalize, id: DurableUploadId) -> Self {
        Self {
            id,
            handle: prepared.handle.clone(),
            action: prepared.action.clone(),
            idempotency_key: prepared.idempotency_key.clone(),
            policy_digest: prepared.policy_digest.clone(),
        }
    }

    /// Returns the trusted durable identity.
    #[must_use]
    pub const fn id(&self) -> &DurableUploadId {
        &self.id
    }

    /// Returns the originating temporary upload identity.
    #[must_use]
    pub const fn handle(&self) -> &UploadHandle {
        &self.handle
    }

    fn matches(&self, request: &FinalizeRequest<'_>) -> bool {
        self.handle == *request.evidence().handle()
            && self.action == *request.action()
            && self.idempotency_key == *request.idempotency_key()
            && self.policy_digest == *request.evidence().policy_digest()
    }
}

impl fmt::Debug for DurableUpload {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("<DurableUpload:redacted>")
    }
}

/// Stage whose partial preparation requires an idempotent compensation attempt.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FinalizeFailureStage {
    /// Durable commit returned an error after preparation.
    Commit,
    /// The host returned preparation facts that did not match the request.
    InvalidPreparation,
}

/// Explicit compensation request retaining the exact prepared operation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FailedFinalize {
    prepared: PreparedFinalize,
    stage: FinalizeFailureStage,
}

impl FailedFinalize {
    fn new(prepared: PreparedFinalize, stage: FinalizeFailureStage) -> Self {
        Self { prepared, stage }
    }

    /// Returns the exact host preparation to compensate.
    #[must_use]
    pub const fn prepared(&self) -> &PreparedFinalize {
        &self.prepared
    }

    /// Returns the stage that triggered compensation.
    #[must_use]
    pub const fn stage(&self) -> FinalizeFailureStage {
        self.stage
    }
}

/// Host-owned durable storage and application-database coordination.
pub trait UploadFinalizer: Send + Sync {
    /// Idempotently prepares storage and domain work for one logical request.
    fn prepare<'a>(
        &'a self,
        request: FinalizeRequest<'a>,
    ) -> UploadFuture<'a, Result<PreparedFinalize, UploadError>>;

    /// Idempotently commits one prepared logical outcome.
    fn commit<'a>(
        &'a self,
        prepared: PreparedFinalize,
    ) -> UploadFuture<'a, Result<DurableUpload, UploadError>>;

    /// Idempotently compensates partial preparation after a failed attempt.
    fn compensate<'a>(
        &'a self,
        failed: FailedFinalize,
    ) -> UploadFuture<'a, Result<(), UploadError>>;

    /// Loads a previously committed outcome for retry or reconciliation.
    fn reconcile<'a>(
        &'a self,
        request: FinalizeRequest<'a>,
    ) -> UploadFuture<'a, Result<Option<DurableUpload>, UploadError>>;
}

/// Trusted request from one already authorized registered action invocation.
pub struct FinalizeUploadRequest {
    handle: UploadHandle,
    field: ModelField,
    ready_revision: UploadRevision,
    idempotency_key: UploadIdempotencyKey,
    action: AuthorizedAction,
    policy: UploadFieldPolicy,
}

impl FinalizeUploadRequest {
    /// Groups the exact Ready revision, logical retry, action proof, and policy.
    #[must_use]
    pub const fn new(
        handle: UploadHandle,
        field: ModelField,
        ready_revision: UploadRevision,
        idempotency_key: UploadIdempotencyKey,
        action: AuthorizedAction,
        policy: UploadFieldPolicy,
    ) -> Self {
        Self {
            handle,
            field,
            ready_revision,
            idempotency_key,
            action,
            policy,
        }
    }
}

impl fmt::Debug for FinalizeUploadRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("<FinalizeUploadRequest:redacted>")
    }
}

/// Whether this call completed new durable work or replayed it.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FinalizeDisposition {
    /// New durable work and the Finalized lifecycle outcome committed.
    Finalized,
    /// The exact logical durable outcome was already committed.
    ExistingOutcome,
}

/// Safe finalization result.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FinalizeUploadOutcome {
    disposition: FinalizeDisposition,
    durable: DurableUpload,
    revision: UploadRevision,
}

impl FinalizeUploadOutcome {
    /// Returns whether durable work was new or replayed.
    #[must_use]
    pub const fn disposition(&self) -> FinalizeDisposition {
        self.disposition
    }

    /// Returns the durable logical upload.
    #[must_use]
    pub const fn durable(&self) -> &DurableUpload {
        &self.durable
    }

    /// Returns the authoritative Finalized upload revision.
    #[must_use]
    pub const fn revision(&self) -> UploadRevision {
        self.revision
    }
}

/// Finalization coordinator preserving action, upload, policy, and retry authority.
pub struct UploadFinalizationService {
    authority: Arc<UploadService>,
    evidence: Arc<dyn UploadValidationStore>,
    finalizer: Arc<dyn UploadFinalizer>,
}

impl UploadFinalizationService {
    /// Creates a service over persistent authority, evidence, and durable host work.
    #[must_use]
    pub fn new(
        authority: Arc<UploadService>,
        evidence: Arc<dyn UploadValidationStore>,
        finalizer: Arc<dyn UploadFinalizer>,
    ) -> Self {
        Self {
            authority,
            evidence,
            finalizer,
        }
    }

    /// Reauthorizes and idempotently finalizes one Ready upload.
    pub async fn finalize(
        &self,
        context: &TrustedLiveRequestContext,
        request: FinalizeUploadRequest,
        now: UnixMillis,
    ) -> Result<FinalizeUploadOutcome, UploadError> {
        if request.action.component() != context.mount().component()
            || request.action.action() != request.policy.finalize_action()
        {
            return Err(UploadError::new(UploadErrorKind::AuthorizationDenied));
        }
        let finalizing_revision = request.ready_revision.checked_next()?;
        let finalized_revision = finalizing_revision.checked_next()?;
        let record = self
            .authority
            .trusted_status(
                context,
                request.field.clone(),
                request.handle.clone(),
                UploadControlKind::BeginFinalize,
                now,
            )
            .await?;
        let coherent_state = match record.state() {
            UploadState::Ready => record.revision() == request.ready_revision,
            UploadState::Finalizing => record.revision() == finalizing_revision,
            UploadState::Finalized => record.revision() == finalized_revision,
            _ => false,
        };
        if !coherent_state {
            return Err(UploadError::new(UploadErrorKind::UploadConflict));
        }
        let evidence = self
            .evidence
            .load(&request.handle)
            .await?
            .ok_or_else(|| UploadError::new(UploadErrorKind::ValidationEvidenceUnavailable))?;
        if evidence.authority() != record.authority()
            || evidence.ready_revision() != request.ready_revision
            || evidence.policy_digest() != request.policy.contract_digest()
        {
            return Err(UploadError::new(
                UploadErrorKind::ValidationEvidenceUnavailable,
            ));
        }

        let begin = self
            .authority
            .trusted_transition(
                context,
                request.field.clone(),
                UploadTransitionRequest::new(
                    request.handle.clone(),
                    request.ready_revision,
                    phase_key(&request.idempotency_key, "begin")?,
                    UploadTransition::BeginFinalize,
                ),
                now,
            )
            .await?;
        if begin.state() != UploadState::Finalizing || begin.revision() != finalizing_revision {
            return Err(UploadError::new(UploadErrorKind::UploadConflict));
        }

        let port_request = FinalizeRequest::new(
            &evidence,
            request.action.action(),
            &request.idempotency_key,
            now,
        );
        let reconciled = self.finalizer.reconcile(port_request).await?;
        if record.state() == UploadState::Finalized && reconciled.is_none() {
            return Err(UploadError::new(UploadErrorKind::ReconciliationRequired));
        }
        let (durable, existing_external) = if let Some(durable) = reconciled {
            if !durable.matches(&port_request) {
                return Err(UploadError::new(UploadErrorKind::ReconciliationRequired));
            }
            (durable, true)
        } else {
            let prepared = self.finalizer.prepare(port_request).await?;
            if !prepared.matches(&port_request) {
                if self
                    .finalizer
                    .compensate(FailedFinalize::new(
                        prepared,
                        FinalizeFailureStage::InvalidPreparation,
                    ))
                    .await
                    .is_err()
                {
                    return Err(UploadError::new(UploadErrorKind::CompensationFailed));
                }
                return Err(UploadError::new(UploadErrorKind::FinalizationFailed));
            }
            let durable = match self.finalizer.commit(prepared.clone()).await {
                Ok(durable) => durable,
                Err(error) => {
                    if self
                        .finalizer
                        .compensate(FailedFinalize::new(prepared, FinalizeFailureStage::Commit))
                        .await
                        .is_err()
                    {
                        return Err(UploadError::new(UploadErrorKind::CompensationFailed));
                    }
                    return Err(error);
                }
            };
            if !durable.matches(&port_request) {
                return Err(UploadError::new(UploadErrorKind::ReconciliationRequired));
            }
            (durable, false)
        };

        let commit = self
            .authority
            .trusted_transition(
                context,
                request.field,
                UploadTransitionRequest::new(
                    request.handle,
                    finalizing_revision,
                    phase_key(&request.idempotency_key, "commit")?,
                    UploadTransition::CommitFinalize,
                ),
                now,
            )
            .await
            .map_err(|_| UploadError::new(UploadErrorKind::ReconciliationRequired))?;
        if commit.state() != UploadState::Finalized || commit.revision() != finalized_revision {
            return Err(UploadError::new(UploadErrorKind::ReconciliationRequired));
        }
        let existing = existing_external
            || begin.disposition() == TransitionDisposition::ExistingOutcome
            || commit.disposition() == TransitionDisposition::ExistingOutcome;
        Ok(FinalizeUploadOutcome {
            disposition: if existing {
                FinalizeDisposition::ExistingOutcome
            } else {
                FinalizeDisposition::Finalized
            },
            durable,
            revision: commit.revision(),
        })
    }
}

impl fmt::Debug for UploadFinalizationService {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("<UploadFinalizationService:redacted>")
    }
}

fn phase_key(
    logical: &UploadIdempotencyKey,
    phase: &str,
) -> Result<UploadIdempotencyKey, UploadError> {
    let mut hasher = Sha256::new();
    hasher.update(b"suprnova-live:upload-finalize-phase:v1\0");
    hasher.update(phase.as_bytes());
    hasher.update([0]);
    hasher.update(logical.as_str().as_bytes());
    let mut digest = String::with_capacity(64);
    for byte in hasher.finalize() {
        write!(&mut digest, "{byte:02x}")
            .map_err(|_| UploadError::new(UploadErrorKind::FinalizationFailed))?;
    }
    UploadIdempotencyKey::parse(&format!("finalize:{phase}:{digest}"))
}

fn parse_finalize_identity(value: &str) -> Result<String, UploadError> {
    let valid = !value.is_empty()
        && value.len() <= MAX_FINALIZE_IDENTITY_BYTES
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b':' | b'.'));
    if valid {
        Ok(value.to_owned())
    } else {
        Err(UploadError::new(UploadErrorKind::InvalidField))
    }
}
