//! File responses: a file streamed from a path, shown inline or sent as a
//! download, generated bytes sent as a download, and the RFC 6266
//! `Content-Disposition` value every one of them writes.
//!
//! Laravel spreads this over `ResponseFactory::file`, `download` and
//! `streamDownload`, with Symfony's `HeaderUtils::makeDisposition` writing
//! the header. Here the constructors live on [`HttpResponse`] and the
//! header on [`ContentDisposition`], and `Storage::download` /
//! `Storage::response` reuse both for a path on a named disk.
//!
//! The pieces [`StaticFiles`](crate::StaticFiles) shares with these
//! responses (the extension table, the buffered-or-streamed body, the
//! stream that ends short on a read failure) live here too, so a file
//! served by either path gets the same content type and the same body
//! handling.

use super::response::HttpResponse;
use crate::error::FrameworkError;
use bytes::Bytes;
use futures::Stream;
use percent_encoding::{AsciiSet, NON_ALPHANUMERIC, utf8_percent_encode};
use std::convert::Infallible;
use std::path::Path;
use std::pin::Pin;
use std::task::{Context, Poll};
use tokio::io::AsyncReadExt;

/// Size of each chunk a streamed file body reads and sends: a few reads
/// per megabyte, while the read-ahead [`FILE_CHUNKS_QUEUED`] bounds stays
/// near one megabyte.
const FILE_CHUNK_SIZE: usize = 256 * 1024;

/// How many chunks a streamed file's reader may have waiting for the
/// response. A client that stops reading holds these, plus the one the
/// reader holds while it waits for room, and no more.
const FILE_CHUNKS_QUEUED: usize = 4;

/// Files at or below this size are read fully into memory and served as a
/// buffered body whose `Content-Length` is the exact number of bytes read.
/// This makes the declared length self-consistent with the body for the
/// common case - there is no window in which the file can change between the
/// `stat` and the read. Larger files keep streaming so a multi-gigabyte
/// download never has to be resident in memory.
pub(crate) const BUFFERED_BODY_LIMIT: u64 = 1024 * 1024;

/// The bytes RFC 8187 lets an extended parameter value (`filename*`) carry
/// as they are: its `attr-char` set. Everything else is written `%XX`.
const ATTR_CHAR: &AsciiSet = &NON_ALPHANUMERIC
    .remove(b'!')
    .remove(b'#')
    .remove(b'$')
    .remove(b'&')
    .remove(b'+')
    .remove(b'-')
    .remove(b'.')
    .remove(b'^')
    .remove(b'_')
    .remove(b'`')
    .remove(b'|')
    .remove(b'~');

/// Whether a browser shows a response body or saves it, and the
/// `Content-Disposition` header value that says so.
///
/// Every file response writes its header through
/// [`header_value`](Self::header_value), so a filename taken from user
/// input (the original name of an upload, say) can never change the
/// header's structure. Use it directly for a response the constructors do
/// not cover, such as a download built on
/// [`HttpResponse::stream_bytes`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContentDisposition {
    /// Show the body in the browser when it can (a PDF, an image); a
    /// filename is still used if the user saves it.
    Inline,
    /// Save the body as a file instead of showing it.
    Attachment,
}

impl ContentDisposition {
    /// The `Content-Disposition` value for `filename`, per RFC 6266.
    ///
    /// The `filename` parameter is an ASCII fallback for clients that read
    /// nothing else, built the way Laravel builds its fallback with
    /// `Str::ascii`: each character outside ASCII is spelled in ASCII
    /// (`é` as `e`, `ß` as `ss`), and one whose spelling would put a
    /// character unsafe in a filename into the name (`·` as `*`, `½` as
    /// `1/2`) is dropped. A character with no spelling at all becomes `_`,
    /// so the fallback never shrinks to nothing. `%` and `/` become `_`,
    /// and `"` and `\` are escaped inside the quoted string.
    ///
    /// When that fallback cannot carry the name exactly, a
    /// `filename*=UTF-8''...` parameter follows with the name
    /// percent-encoded (RFC 8187), which every current browser prefers.
    ///
    /// Control characters (CR, LF, NUL, DEL and the C1 range) are replaced
    /// by `_` in both forms before anything else, so none of them reaches
    /// the header, raw or encoded. An empty `filename` writes the
    /// disposition type alone.
    ///
    /// ```rust
    /// use suprnova::ContentDisposition;
    ///
    /// assert_eq!(
    ///     ContentDisposition::Attachment.header_value("Joan Pérez.pdf"),
    ///     "attachment; filename=\"Joan Perez.pdf\"; filename*=UTF-8''Joan%20P%C3%A9rez.pdf"
    /// );
    /// assert_eq!(
    ///     ContentDisposition::Inline.header_value("report.pdf"),
    ///     "inline; filename=\"report.pdf\""
    /// );
    /// ```
    pub fn header_value(self, filename: &str) -> String {
        let kind = match self {
            Self::Inline => "inline",
            Self::Attachment => "attachment",
        };
        if filename.is_empty() {
            return kind.to_owned();
        }

        let name: String = filename
            .chars()
            .map(|c| if c.is_control() { '_' } else { c })
            .collect();

        let mut value = String::with_capacity(kind.len() + 2 * name.len() + 32);
        value.push_str(kind);
        value.push_str("; filename=\"");
        let mut exact = true;
        for c in name.chars() {
            match c {
                '"' | '\\' => {
                    // Escaping is exact per RFC 9110, but some clients do
                    // not unescape; `filename*` gives them the true name.
                    exact = false;
                    value.push('\\');
                    value.push(c);
                }
                '%' | '/' => {
                    // RFC 6266 appendix D: some clients percent-decode the
                    // fallback, so `%` is kept out of it; `/` would make the
                    // name a path.
                    exact = false;
                    value.push('_');
                }
                ' '..='~' => value.push(c),
                _ => {
                    exact = false;
                    push_spelling(&mut value, c);
                }
            }
        }
        value.push('"');
        if !exact {
            value.push_str("; filename*=UTF-8''");
            value.extend(utf8_percent_encode(&name, ATTR_CHAR));
        }
        value
    }
}

/// Append the ASCII spelling of the non-ASCII `c` to the `filename`
/// fallback.
///
/// Laravel's `Str::ascii` spells what it can and drops the rest; `deunicode`
/// spells far more (it has an answer for `·`, `½` and most symbols), so a
/// spelling is kept only when every character of it is safe in a filename.
/// A character `deunicode` cannot spell at all becomes `_` instead of
/// vanishing, so a name made only of such characters still has a fallback.
fn push_spelling(fallback: &mut String, c: char) {
    match deunicode::deunicode_char(c) {
        None => fallback.push('_'),
        Some(spelling) if spelling.chars().all(safe_in_fallback) => fallback.push_str(spelling),
        Some(_) => {}
    }
}

/// Whether a character of a transliteration may stand in the fallback as
/// it is: printable ASCII that is neither a path separator, `%`, a
/// character Windows refuses in a filename, nor one the quoted string would
/// have to escape.
fn safe_in_fallback(c: char) -> bool {
    matches!(c, ' '..='~')
        && !matches!(
            c,
            '"' | '\\' | '/' | '%' | '*' | '?' | ':' | '<' | '>' | '|'
        )
}

impl HttpResponse {
    /// Stream the file at `path` for the browser to show: Laravel's
    /// `response()->file($path)`.
    ///
    /// The response carries the content type the file's extension implies
    /// (`application/octet-stream` when it implies none; the content is
    /// never sniffed, so a file with an unknown extension is never served
    /// as HTML or SVG), a `Content-Length`, and
    /// `Content-Disposition: inline` with `name`,
    /// or the file's own name when `name` is `None`. A file above 1 MiB is
    /// streamed in 256 KiB chunks rather than read into memory.
    ///
    /// `path` is opened as given. Never build it from request input: for
    /// a file a user names, use `Storage::response` on a disk, whose path
    /// guard refuses `..`.
    ///
    /// # Errors
    ///
    /// A 404 error when nothing is at `path` or it is not a file; a 500
    /// error when the file cannot be opened or read. The 404 message names
    /// no path; a 500 renders the generic server-error body, so its path
    /// reaches the log (and the debug-only `debug_message`), not the
    /// client. Convert with `.map_err(HttpResponse::from)` in a
    /// handler that returns [`Response`](crate::Response).
    ///
    /// ```rust,no_run
    /// use suprnova::{HttpResponse, Request, Response};
    ///
    /// async fn certificate(_req: Request) -> Response {
    ///     HttpResponse::file("storage/certificates/7f3e.pdf", Some("certificate.pdf"))
    ///         .await
    ///         .map_err(HttpResponse::from)
    /// }
    /// ```
    pub async fn file(
        path: impl AsRef<Path>,
        name: Option<&str>,
    ) -> Result<HttpResponse, FrameworkError> {
        path_response(path.as_ref(), name, ContentDisposition::Inline).await
    }

    /// Stream the file at `path` as a download: Laravel's
    /// `response()->download($path, $name)`.
    ///
    /// The same response as [`HttpResponse::file`], but
    /// `Content-Disposition: attachment`, so the browser saves the file
    /// under `name` (or the file's own name when `name` is `None`). The
    /// name is written per RFC 6266 by
    /// [`ContentDisposition::header_value`], so the original name of an
    /// upload, accents and all, is safe to pass.
    ///
    /// # Errors
    ///
    /// The same as [`HttpResponse::file`].
    ///
    /// ```rust,no_run
    /// use suprnova::{HttpResponse, Request, Response};
    ///
    /// async fn attachment(_req: Request) -> Response {
    ///     HttpResponse::download("storage/attachments/7f3e", Some("Informe Pérez.pdf"))
    ///         .await
    ///         .map_err(HttpResponse::from)
    /// }
    /// ```
    pub async fn download(
        path: impl AsRef<Path>,
        name: Option<&str>,
    ) -> Result<HttpResponse, FrameworkError> {
        path_response(path.as_ref(), name, ContentDisposition::Attachment).await
    }

    /// Send bytes generated in memory as a download named `name`, with
    /// the given `content_type`: the case Laravel covers with
    /// `streamDownload` (an export built on the fly, say).
    ///
    /// Nothing is read from disk, so this cannot fail. The name is written
    /// per RFC 6266 by [`ContentDisposition::header_value`].
    ///
    /// ```rust,no_run
    /// use suprnova::{HttpResponse, Request, Response};
    ///
    /// async fn export(_req: Request) -> Response {
    ///     let csv = "id,name\n1,Joan\n".to_string();
    ///     Ok(HttpResponse::download_bytes(csv, "users-2026-09-30.csv", "text/csv; charset=utf-8"))
    /// }
    /// ```
    pub fn download_bytes(
        body: impl Into<Bytes>,
        name: &str,
        content_type: impl Into<String>,
    ) -> HttpResponse {
        HttpResponse::bytes_body(body, content_type).header(
            "Content-Disposition",
            ContentDisposition::Attachment.header_value(name),
        )
    }
}

/// The response `file` and `download` share; only the disposition differs.
async fn path_response(
    path: &Path,
    name: Option<&str>,
    disposition: ContentDisposition,
) -> Result<HttpResponse, FrameworkError> {
    let file = tokio::fs::File::open(path)
        .await
        .map_err(|error| io_error(path, error))?;
    let metadata = file
        .metadata()
        .await
        .map_err(|error| io_error(path, error))?;
    if !metadata.is_file() {
        return Err(file_not_found());
    }

    let own_name = path
        .file_name()
        .map(|own| own.to_string_lossy().into_owned())
        .unwrap_or_default();
    let filename = name.unwrap_or(&own_name);

    let response = file_body(file, metadata.len(), content_type_from_extension(path))
        .await
        .map_err(|error| io_error(path, error))?;
    Ok(response.header("Content-Disposition", disposition.header_value(filename)))
}

/// The 404 error every file response answers for a file that is not
/// there. The message names no path, so it can reach the client.
pub(crate) fn file_not_found() -> FrameworkError {
    FrameworkError::not_found("File")
}

/// Map an I/O error on `path` to the error a handler can answer with: a
/// missing file is a 404, anything else a 500 whose message (with the
/// path) only reaches the log.
fn io_error(path: &Path, error: std::io::Error) -> FrameworkError {
    use std::io::ErrorKind;
    match error.kind() {
        ErrorKind::NotFound | ErrorKind::NotADirectory | ErrorKind::IsADirectory => {
            file_not_found()
        }
        _ => FrameworkError::from_external_with(
            format!("file response: could not read {}", path.display()),
            error,
        ),
    }
}

/// The response for an open `file` of `length` bytes: buffered when it
/// is at most [`BUFFERED_BODY_LIMIT`], streamed otherwise. Either way it
/// carries `Content-Type` and `Content-Length`.
///
/// The buffered read stops at `length`, so a file that grows after the
/// `stat` can never make the read unbounded; the `Content-Length` is the
/// count actually read.
pub(crate) async fn file_body(
    file: tokio::fs::File,
    length: u64,
    content_type: String,
) -> std::io::Result<HttpResponse> {
    if length <= BUFFERED_BODY_LIMIT {
        let mut buffer = Vec::with_capacity(length as usize);
        file.take(length).read_to_end(&mut buffer).await?;
        let read = buffer.len();
        Ok(HttpResponse::bytes_body(Bytes::from(buffer), content_type)
            .header("Content-Length", read.to_string()))
    } else {
        // The declared `Content-Length` is the stat size; if the file is
        // truncated or a read fails mid-flight the stream stops short of
        // that length, so hyper's length-delimited encoder reaches
        // end-of-stream with bytes still owed and aborts the connection
        // rather than completing a short body cleanly.
        Ok(
            HttpResponse::stream_bytes(FileByteStream::new(file.into_std().await, length))
                .header("Content-Type", content_type)
                .header("Content-Length", length.to_string()),
        )
    }
}

/// The `Content-Type` a file response sends for `path`: the type its
/// extension implies, or `application/octet-stream`. Never sniffed from
/// the content, for the reason given on [`HttpResponse::file`].
pub(crate) fn content_type_from_extension(path: &Path) -> String {
    with_charset(mime_from_extension(path).unwrap_or("application/octet-stream"))
}

/// `mime` as a `Content-Type` value, with `; charset=utf-8` added to the
/// textual types a browser would otherwise decode with a guessed charset.
pub(crate) fn with_charset(mime: &str) -> String {
    if should_add_charset(mime) {
        format!("{mime}; charset=utf-8")
    } else {
        mime.to_string()
    }
}

/// The MIME type a file's extension implies, matched case-insensitively,
/// or `None` for an extension this table does not know.
pub(crate) fn mime_from_extension(path: &Path) -> Option<&'static str> {
    let ext = path.extension()?.to_str()?.to_ascii_lowercase();
    Some(match ext.as_str() {
        "aac" => "audio/aac",
        "avif" => "image/avif",
        "bin" => "application/octet-stream",
        "bmp" => "image/bmp",
        "br" => "application/octet-stream",
        "css" => "text/css",
        "csv" => "text/csv",
        "doc" => "application/msword",
        "docx" => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "eot" => "application/vnd.ms-fontobject",
        "gif" => "image/gif",
        "gz" => "application/gzip",
        "htm" | "html" => "text/html",
        "ico" => "image/x-icon",
        "jpeg" | "jpg" => "image/jpeg",
        "js" | "mjs" => "text/javascript",
        "json" | "map" => "application/json",
        "md" => "text/markdown",
        "mp3" => "audio/mpeg",
        "mp4" => "video/mp4",
        "odp" => "application/vnd.oasis.opendocument.presentation",
        "ods" => "application/vnd.oasis.opendocument.spreadsheet",
        "odt" => "application/vnd.oasis.opendocument.text",
        "oga" => "audio/ogg",
        "ogg" => "audio/ogg",
        "ogv" => "video/ogg",
        "otf" => "font/otf",
        "pdf" => "application/pdf",
        "png" => "image/png",
        "ppt" => "application/vnd.ms-powerpoint",
        "pptx" => "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "rtf" => "application/rtf",
        "svg" => "image/svg+xml",
        "tar" => "application/x-tar",
        "text" | "txt" => "text/plain",
        "ttf" => "font/ttf",
        "wasm" => "application/wasm",
        "wav" => "audio/wav",
        "webm" => "video/webm",
        "webmanifest" => "application/manifest+json",
        "webp" => "image/webp",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "xls" => "application/vnd.ms-excel",
        "xlsx" => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xml" => "application/xml",
        "zip" => "application/zip",
        _ => return None,
    })
}

fn should_add_charset(mime: &str) -> bool {
    mime.starts_with("text/")
        || matches!(
            mime,
            "application/javascript"
                | "application/json"
                | "application/manifest+json"
                | "application/xml"
                | "image/svg+xml"
                | "text/javascript"
                | "text/xml"
        )
        || mime.ends_with("+json")
        || mime.ends_with("+xml")
}

/// Streaming body for files above [`BUFFERED_BODY_LIMIT`].
///
/// The body declares a `Content-Length` equal to `remaining` at construction.
/// The stream caps its output at that length and stops as soon as the
/// underlying file returns end-of-file or an error. If that happens before
/// `remaining` reaches zero - a truncated file or a mid-flight read failure -
/// the stream yields its terminal `None` with bytes still owed, leaving
/// hyper's length-delimited encoder short of the promised body. hyper then
/// fails the response with a body-write-aborted error and resets the
/// connection, so the client sees a broken transfer rather than a cleanly
/// completed body that is silently shorter than its `Content-Length`. The
/// framework's streaming bodies are `Infallible`, so this short-body abort is
/// how a read failure is surfaced to the client.
///
/// The first poll starts one blocking task that owns the file for the whole
/// body: it reads [`FILE_CHUNK_SIZE`] chunks in a loop and hands each to the
/// stream over a channel of [`FILE_CHUNKS_QUEUED`]. The body is one trip
/// through the blocking pool rather than one per chunk, so a long download
/// does not compete with every other blocking task chunk by chunk. A client
/// that stops reading leaves the reader waiting for room with at most those
/// chunks read; a dropped stream closes the channel, which stops the reader
/// at its next hand-off; and a body that is never polled, such as the one a
/// `HEAD` response drops, never starts a reader.
///
/// Each chunk is read straight into the buffer it is sent in, allocated for
/// the read about to fill it: one allocation per chunk, and none for a poll
/// that finds no chunk ready. `tokio::fs::File` would read into its own
/// buffer and copy into the caller's.
struct FileByteStream {
    state: ReadState,
    remaining: u64,
}

/// Where a [`FileByteStream`] is in its body.
enum ReadState {
    /// Not polled yet: the file waits for the reader the first poll starts.
    Unstarted(std::fs::File),
    /// The reader owns the file and sends what each read returned here.
    Reading(tokio::sync::mpsc::Receiver<std::io::Result<Vec<u8>>>),
    /// The body ended. The channel is closed, so a reader still running
    /// stops at its next hand-off.
    Ended,
}

impl FileByteStream {
    fn new(file: std::fs::File, content_length: u64) -> Self {
        Self {
            state: ReadState::Unstarted(file),
            remaining: content_length,
        }
    }

    /// End the body, short of its length when bytes are still owed.
    fn finish(&mut self) -> Poll<Option<Result<Bytes, Infallible>>> {
        self.state = ReadState::Ended;
        Poll::Ready(None)
    }
}

/// Start the one blocking task that reads `length` bytes of `file` for a
/// body, and return the channel its reads arrive on.
fn read_in_background(
    file: std::fs::File,
    length: u64,
) -> tokio::sync::mpsc::Receiver<std::io::Result<Vec<u8>>> {
    let (sender, receiver) = tokio::sync::mpsc::channel(FILE_CHUNKS_QUEUED);
    // Not awaited: the reader returns by itself after its last send, and
    // a dropped stream makes its next send fail.
    drop(tokio::task::spawn_blocking(move || {
        read_file(file, length, &sender)
    }));
    receiver
}

/// The reader's loop: read `length` bytes of `file` a chunk at a time and
/// send each read's result. It stops after the last chunk, after an empty
/// read (the file shrank) or a read error, both of which it sends for the
/// stream to report, or when a send fails because the stream was dropped.
fn read_file(
    mut file: std::fs::File,
    length: u64,
    chunks: &tokio::sync::mpsc::Sender<std::io::Result<Vec<u8>>>,
) {
    let mut left = length;
    while left > 0 {
        let size = usize::try_from(left).map_or(FILE_CHUNK_SIZE, |left| left.min(FILE_CHUNK_SIZE));
        let read = read_chunk(&mut file, vec![0; size]);
        let stop = match &read {
            Ok(chunk) => {
                left = left.saturating_sub(chunk.len() as u64);
                chunk.is_empty()
            }
            Err(_) => true,
        };
        if chunks.blocking_send(read).is_err() || stop {
            return;
        }
    }
}

/// Fill `buffer` from `file`, retrying a read a signal interrupted, and
/// return it cut to what was read, which is shorter only at end of file.
fn read_chunk(file: &mut std::fs::File, mut buffer: Vec<u8>) -> std::io::Result<Vec<u8>> {
    use std::io::Read;
    let mut filled = 0;
    while filled < buffer.len() {
        match file.read(&mut buffer[filled..]) {
            Ok(0) => break,
            Ok(read) => filled += read,
            Err(error) if error.kind() == std::io::ErrorKind::Interrupted => {}
            Err(error) => return Err(error),
        }
    }
    buffer.truncate(filled);
    Ok(buffer)
}

impl Stream for FileByteStream {
    type Item = Result<Bytes, Infallible>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.get_mut();
        if this.remaining == 0 {
            return this.finish();
        }
        this.state = match std::mem::replace(&mut this.state, ReadState::Ended) {
            ReadState::Unstarted(file) => {
                ReadState::Reading(read_in_background(file, this.remaining))
            }
            state => state,
        };
        let ReadState::Reading(chunks) = &mut this.state else {
            return Poll::Ready(None);
        };
        match std::task::ready!(chunks.poll_recv(cx)) {
            Some(Ok(chunk)) if chunk.is_empty() => {
                tracing::warn!(
                    owed = this.remaining,
                    "file shrank mid-stream; ending body short so \
                     the connection aborts instead of serving a truncated payload"
                );
                this.finish()
            }
            Some(Ok(chunk)) => {
                this.remaining = this.remaining.saturating_sub(chunk.len() as u64);
                Poll::Ready(Some(Ok(Bytes::from(chunk))))
            }
            Some(Err(error)) => {
                tracing::warn!(
                    error = %error,
                    owed = this.remaining,
                    "file stream read failed; ending body short so the \
                     connection aborts instead of completing a partial payload"
                );
                this.finish()
            }
            None => {
                tracing::warn!(
                    owed = this.remaining,
                    "file stream read task failed; ending body short so the \
                     connection aborts instead of completing a partial payload"
                );
                this.finish()
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use futures::StreamExt;
    use tokio::io::AsyncWriteExt;

    #[tokio::test]
    async fn file_byte_stream_never_exceeds_captured_length() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("asset.bin");
        tokio::fs::write(&path, b"abc").await.expect("write seed");

        let file = tokio::fs::File::open(&path)
            .await
            .expect("open stream file");
        let captured_len = 3;

        let mut append = tokio::fs::OpenOptions::new()
            .append(true)
            .open(&path)
            .await
            .expect("open append handle");
        append.write_all(b"def").await.expect("append growth");
        append.flush().await.expect("flush growth");
        drop(append);

        let mut stream = FileByteStream::new(file.into_std().await, captured_len);
        let mut emitted = Vec::new();
        while let Some(chunk) = stream.next().await {
            emitted.extend_from_slice(&chunk.expect("infallible stream chunk"));
        }

        assert_eq!(emitted, b"abc");
    }

    #[tokio::test]
    async fn file_byte_stream_ends_short_when_file_shrinks() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("asset.bin");
        tokio::fs::write(&path, b"abcdefghij")
            .await
            .expect("write seed");

        let file = tokio::fs::File::open(&path)
            .await
            .expect("open stream file");
        // The body promised ten bytes...
        let captured_len = 10;

        // ...but the file is truncated to three before any chunk is read.
        let truncate = tokio::fs::OpenOptions::new()
            .write(true)
            .open(&path)
            .await
            .expect("open truncate handle");
        truncate.set_len(3).await.expect("shrink file");
        truncate.sync_all().await.expect("sync shrink");
        drop(truncate);

        let mut stream = FileByteStream::new(file.into_std().await, captured_len);
        let mut emitted = Vec::new();
        while let Some(chunk) = stream.next().await {
            emitted.extend_from_slice(&chunk.expect("infallible stream chunk"));
        }

        // Fewer bytes than promised are emitted, and the stream finishes with
        // bytes still owed. hyper's length-delimited encoder reaches EOF below
        // the declared Content-Length and aborts the connection instead of
        // completing a silently-truncated body.
        assert_eq!(emitted, b"abc");
        assert!(emitted.len() < captured_len as usize);
        assert!(stream.remaining > 0, "shrunken file must leave bytes owed");
        assert!(matches!(stream.state, ReadState::Ended));
    }

    #[tokio::test]
    async fn a_buffered_body_stops_at_the_stat_length_when_the_file_grows() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("grows.txt");
        tokio::fs::write(&path, b"abc").await.expect("write seed");
        let file = tokio::fs::File::open(&path).await.expect("open");

        tokio::fs::write(&path, b"abcdef").await.expect("grow");

        let response = file_body(file, 3, "text/plain".into())
            .await
            .expect("buffered body");
        assert!(!response.is_streaming());
        assert_eq!(response.body(), b"abc");
        assert_eq!(response.header_value("Content-Length"), Some("3"));
    }
}
