"""Write framework/src/strings/inflector_rules.rs from doctrine/inflector.

Usage: python3 feature-map/tools/laravel/strings_inflector.py <laravel-dir> <out.rs> && cargo fmt

<laravel-dir> is the Laravel checkout feature-map/tools/laravel/generate.sh
installs (target/feature-map/laravel/framework-<version>), so the rules are
the doctrine/inflector release that Laravel version resolves. The rule
sets are read from doctrine's PHP sources for the six languages
`Str::plural` and `Str::singular` offer: PHP patterns become Rust regexes,
`\\1` replacements become `${1}`, and the one lookbehind, English
`([ti])a(?<!regatta)$`, becomes the pattern without it plus a suffix the
word must not end with.
"""
import json
import pathlib
import re
import sys

LANGS = [
    ("English", "ENGLISH"),
    ("French", "FRENCH"),
    ("NorwegianBokmal", "NORWEGIAN_BOKMAL"),
    ("Portuguese", "PORTUGUESE"),
    ("Spanish", "SPANISH"),
    ("Turkish", "TURKISH"),
]
LIT = r"'((?:[^'\\]|\\.)*)'"


def php(s):
    """The value of a PHP single-quoted literal's body."""
    return re.sub(r"\\([\\'])", r"\1", s)


def functions(path):
    text = path.read_text()
    out = {}
    for m in re.finditer(
        r"(?:public|private) static function (\w+)\(\): iterable\s*\{(.*?)\n    \}", text, re.S
    ):
        out[m.group(1)] = m.group(2)
    return out


def items(body, fns):
    res = []
    for line in body.splitlines():
        line = line.strip()
        if not line.startswith("yield"):
            continue
        if line.startswith("yield from self::"):
            name = re.match(r"yield from self::(\w+)\(\);", line).group(1)
            res += items(fns[name], fns)
            continue
        m = re.match(r"yield new Transformation\(new Pattern\(" + LIT + r"\), " + LIT + r"\);$", line)
        if m:
            res.append(("t", php(m.group(1)), php(m.group(2))))
            continue
        m = re.match(r"yield new Substitution\(new Word\(" + LIT + r"\), new Word\(" + LIT + r"\)\);$", line)
        if m:
            res.append(("s", php(m.group(1)), php(m.group(2))))
            continue
        m = re.match(r"yield new Pattern\(" + LIT + r"\);$", line)
        if m:
            res.append(("p", php(m.group(1))))
            continue
        sys.exit("unparsed: " + line)
    return res


def regex(p):
    if p.startswith("/"):
        last = p.rindex("/")
        body, flags = p[1:last], p[last + 1:]
        assert set(flags) <= set("iu"), p
        return ("(?i)" if "i" in flags else "") + body
    return "(?i)" + p


def repl(r):
    r = r.replace("$", "$$")
    return re.sub(r"\\(\d)", r"${\1}", r)


def raw(s):
    assert '"#' not in s
    return 'r#"' + s + '"#'


def main():
    laravel, out_path = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    package = laravel / "vendor/doctrine/inflector"
    installed = json.loads((laravel / "vendor/composer/installed.json").read_text())
    version = next(p["version"] for p in installed["packages"] if p["name"] == "doctrine/inflector")
    rules = package / "src/Rules"
    notice = "".join(
        ("//\n" if not line.strip() else "// " + line + "\n")
        for line in (package / "LICENSE").read_text().rstrip().splitlines()
    )
    out = [
        f"""// doctrine/inflector {version}, whose rule data this file transcribes, is
// distributed under this license:
//
{notice}
//! doctrine/inflector {version}'s rule sets for the six languages Laravel's
//! `Pluralizer` offers, the release Laravel installs, transcribed from its
//! PHP sources: the patterns as Rust regexes, `\\1` replacements as `${{1}}`.
//! Each list keeps doctrine's order, which decides which rule wins. The
//! one lookbehind, English `([ti])a(?<!regatta)$`, becomes the pattern
//! without it and a suffix the word must not end with, the third field.
//!
//! Generated by `feature-map/tools/laravel/strings_inflector.py`; edit that,
//! not this file.

use super::inflector::{{LanguageRules, RuleList}};
"""
    ]
    for lang, const in LANGS:
        inf = functions(rules / lang / "Inflectible.php")
        un = functions(rules / lang / "Uninflected.php")

        def tlist(kind):
            rows = items(inf[kind], inf)
            assert all(r[0] == "t" for r in rows), (lang, kind)

            def row(a, b):
                r = regex(a)
                unless = ""
                m = re.search(r"\(\?<!([^)]*)\)\$$", r)
                if m:
                    unless = m.group(1)
                    r = r[: m.start()] + "$"
                assert "(?<" not in r and "(?=" not in r and "(?!" not in r, r
                return f"            ({raw(r)}, {raw(repl(b))}, {raw(unless)}),\n"

            return "&[\n" + "".join(row(a, b) for _, a, b in rows) + "        ]"

        def plist(kind):
            rows = items(un[kind], un)
            assert all(r[0] == "p" for r in rows), (lang, kind)
            return "&[" + ", ".join(raw(r[1]) for r in rows) + "]"

        irr = items(inf["getIrregular"], inf)
        assert all(r[0] == "s" for r in irr)
        out.append(
            f"""
/// {lang}.
pub(super) const {const}: LanguageRules = LanguageRules {{
    singular: RuleList {{
        transformations: {tlist('getSingular')},
        uninflected: {plist('getSingular')},
    }},
    plural: RuleList {{
        transformations: {tlist('getPlural')},
        uninflected: {plist('getPlural')},
    }},
    irregular: &[{', '.join(f'({raw(a)}, {raw(b)})' for _, a, b in irr)}],
}};
"""
        )
    out_path.write_text("".join(out))
    print(f"{out_path}: doctrine/inflector {version}")


if __name__ == "__main__":
    main()
