<?php
// Write framework/src/strings/ascii_map.rs from voku/portable-ascii.
//
// Usage: php feature-map/tools/laravel/strings_ascii.php <laravel-dir> <out.rs> && cargo fmt
//
// <laravel-dir> is the Laravel checkout feature-map/tools/laravel/generate.sh
// installs (target/feature-map/laravel/framework-<version>). Laravel's
// Str::ascii calls ASCII::to_ascii with the language `en`, which replaces
// text through one map: every language's map merged in file order, then
// the `en` map over it. This reads that map through voku's own private
// helpers, so the table is the one Laravel uses, and writes it sorted by
// key for a binary search.

declare(strict_types=1);

[$self, $laravel, $out] = $argv + [null, null, null];
if ($laravel === null || $out === null) {
    fwrite(STDERR, "usage: php strings_ascii.php <laravel-dir> <out.rs>\n");
    exit(2);
}
require $laravel . '/vendor/autoload.php';

use voku\helper\ASCII;

$all = (new ReflectionMethod(ASCII::class, 'getAsciiAllReplacementMap'))->invoke(null, false, false);
$en = (new ReflectionMethod(ASCII::class, 'getAsciiLanguageReplacementMap'))->invoke(null, 'en', false, false);
$map = array_merge([], $all, $en);

$entries = [];
foreach ($map as $from => $to) {
    $entries[(string) $from] = (string) $to;
}
ksort($entries, SORT_STRING);

$installed = json_decode(file_get_contents($laravel . '/vendor/composer/installed.json'), true);
$version = '';
foreach ($installed['packages'] as $package) {
    if ($package['name'] === 'voku/portable-ascii') {
        $version = $package['version'];
    }
}

$license = rtrim(file_get_contents($laravel . '/vendor/voku/portable-ascii/LICENSE.txt'));
$notice = '';
foreach (explode("\n", $license) as $line) {
    $notice .= trim($line) === '' ? "//\n" : '// ' . rtrim($line) . "\n";
}

$rust = static function (string $s): string {
    $escaped = '';
    foreach (mb_str_split($s) as $char) {
        $code = mb_ord($char);
        $escaped .= match (true) {
            $char === '"' => '\\"',
            $char === '\\' => '\\\\',
            $code >= 0x20 && $code < 0x7F => $char,
            default => sprintf('\\u{%x}', $code),
        };
    }
    return '"' . $escaped . '"';
};

$body = "// voku/portable-ascii $version, whose replacement map this file transcribes,\n"
    . "// is distributed under this license:\n//\n" . $notice . "\n"
    . "//! The replacement map Laravel's `Str::ascii` uses: voku/portable-ascii\n"
    . "//! $version's `to_ascii` with the language `en`, every language's map\n"
    . "//! merged and the `en` map over it, sorted by key.\n"
    . "//!\n"
    . "//! Generated by `feature-map/tools/laravel/strings_ascii.php`; edit that,\n"
    . "//! not this file.\n\n"
    . "/// Each key and the ASCII that replaces it, sorted by key.\n"
    . "pub(super) const MAP: &[(&str, &str)] = &[\n";
foreach ($entries as $from => $to) {
    $body .= '    (' . $rust((string) $from) . ', ' . $rust($to) . "),\n";
}
$body .= "];\n";

file_put_contents($out, $body);
echo "$out: voku/portable-ascii $version, " . count($entries) . " entries\n";
